//! One configured MCP server, as stored in settings.
//!
//! Mirrors `EmailAccount`'s conventions deliberately: a frontend-generated UUID
//! as the stable key, a human label, a per-server `enabled` toggle, and
//! camelCase serde so one object round-trips through `invoke` untranslated.
//! Anything that reads as "how is this different from an email account" should
//! have an answer, and mostly does not.
//!
//! # Secrets
//!
//! Secrets collected during guided setup live in this struct, and therefore in
//! the settings blob — the same trust level as the Brave key, the
//! remote-inference key and CalDAV passwords. Email passwords have since moved
//! to the system keychain (`secrets.rs`, `email/auth.rs`); the rest are meant
//! to follow by the same route, all at once, rather than one integration at a
//! time.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// How a configured server came to exist.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ts_rs::TS)]
#[ts(export)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum McpServerSource {
    /// Installed from the bundled catalog. `entryId` is the catalog entry's id,
    /// which is what lets a later app version notice a version bump.
    #[serde(rename_all = "camelCase")]
    Catalog { entry_id: String },
    /// Tier 3: the user supplied a command directly. No catalog entry, no
    /// guided setup, and the same approval rules — a hand-configured server is
    /// not more trusted than a curated one.
    #[serde(rename_all = "camelCase")]
    Custom {
        program: String,
        #[serde(default)]
        args: Vec<String>,
    },
    /// A server reached over the network rather than spawned. Nothing is
    /// installed, so there is no server directory and no runtime involved; the
    /// credential, when there is one, lives in `secrets` under
    /// [`REMOTE_TOKEN_KEY`] like every other MCP secret.
    #[serde(rename_all = "camelCase")]
    Remote { url: String },
}

/// Where a remote server's bearer token lives in `secrets`.
///
/// A named constant rather than a literal in three places: the settings UI
/// writes it, the spawn path reads it, and a typo between them would produce a
/// server that authenticates as nobody with no error to explain it.
pub const REMOTE_TOKEN_KEY: &str = "remoteToken";

/// A server the user has added.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, ts_rs::TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct McpServerConfig {
    /// Stable UUID, generated by the frontend when the user adds the server.
    /// Used as the lookup key so relabelling does not break a running session
    /// or an in-flight tool reference.
    pub id: String,

    /// Human-facing label. Defaults to the catalog entry's name, but the user
    /// can have two GitHub servers for two accounts.
    pub label: String,

    /// Master per-server toggle. When false the server is not started and its
    /// tools do not reach the agent.
    pub enabled: bool,

    pub source: McpServerSource,

    /// Secrets collected during guided setup, keyed by the step's `key`. A
    /// catalog entry's `env` refers to these as `$secret.<key>`.
    #[serde(default)]
    pub secrets: BTreeMap<String, String>,

    /// The `secrets` keys whose values are kept in the secret store, under
    /// `mcp:<id>:<key>`, with an empty value in `secrets`. Rust reads them only
    /// when it launches the server, runs a setup command or connects.
    #[serde(default)]
    #[ts(optional)]
    pub stored_secrets: Option<Vec<String>>,

    /// Per-tool enablement, keyed by the tool's own name. A tool absent from
    /// this map has never been decided on and falls back to the catalog
    /// entry's tested `defaultTools`; Phase 05 owns that resolution.
    #[serde(default)]
    pub tool_enabled: BTreeMap<String, bool>,

    /// Whether this server's traffic goes through the app's proxy.
    ///
    /// Defaults to following the app setting, which already never proxies
    /// loopback. The override is an escape hatch for the cases an address
    /// cannot decide: a public host the user wants reached direct, or an
    /// internal one that does need the proxy despite the bypass rules.
    ///
    /// Only meaningful for a remote server. A stdio server communicates over a
    /// pipe — there is no connection to proxy — so this is ignored for one, and
    /// the UI does not offer it.
    #[serde(default)]
    pub proxy_use: crate::proxy::ProxyUse,

    /// Whether the guided setup ran to completion. A server whose setup was
    /// abandoned halfway is configured but not startable, and the UI has to be
    /// able to say which.
    #[serde(default)]
    pub setup_complete: bool,

    /// Directories an `addon` setup step has been installed into.
    ///
    /// Lives here rather than in the wizard's own progress because a companion
    /// addon is per project: a user who adds a second Godot project needs the
    /// addon there too, long after setup finished. The settings row reads this
    /// to show where it went and to offer another project.
    #[serde(default)]
    pub addon_projects: Vec<String>,
}

/// By hand, so a `{:?}` in a log or an error shows which secrets are set but
/// never their values.
impl std::fmt::Debug for McpServerConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let Self {
            id,
            label,
            enabled,
            source,
            secrets,
            stored_secrets,
            tool_enabled,
            proxy_use,
            setup_complete,
            addon_projects,
        } = self;
        let secrets: BTreeMap<&str, &str> = secrets
            .iter()
            .map(|(k, v)| (k.as_str(), crate::text_util::redacted(v)))
            .collect();
        f.debug_struct("McpServerConfig")
            .field("id", id)
            .field("label", label)
            .field("enabled", enabled)
            .field("source", source)
            .field("secrets", &secrets)
            .field("stored_secrets", stored_secrets)
            .field("tool_enabled", tool_enabled)
            .field("proxy_use", proxy_use)
            .field("setup_complete", setup_complete)
            .field("addon_projects", addon_projects)
            .finish()
    }
}

/// Where a server's setup secret is kept in the secret store.
pub fn secret_store_key(server_id: &str, key: &str) -> String {
    format!("mcp:{server_id}:{key}")
}

impl McpServerConfig {
    /// This config with every stored secret read back into `secrets`. Called
    /// at the point of use, inside Rust, so the values never cross to the
    /// webview.
    pub async fn resolved(&self) -> Result<McpServerConfig, String> {
        let mut out = self.clone();
        for key in self.stored_secrets.iter().flatten() {
            let value = crate::secrets::require(
                &secret_store_key(&self.id, key),
                &format!("'{key}' value for {}", self.label),
            )
            .await?;
            out.secrets.insert(key.clone(), value);
        }
        Ok(out)
    }

    /// Whether this server should be started: enabled, and finished being set
    /// up. Custom and remote servers have no setup steps, so they are complete
    /// by construction — but the flag is still what decides, so every path
    /// shares one rule.
    pub fn is_startable(&self) -> bool {
        self.enabled && self.setup_complete
    }

    /// The URL for a remote server, if this is one.
    pub fn remote_url(&self) -> Option<&str> {
        match &self.source {
            McpServerSource::Remote { url } => Some(url),
            _ => None,
        }
    }

    /// The pasted credential for a remote server.
    pub fn remote_token(&self) -> Option<&str> {
        self.secrets.get(REMOTE_TOKEN_KEY).map(String::as_str)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn catalog_server() -> McpServerConfig {
        McpServerConfig {
            id: "11111111-1111-1111-1111-111111111111".into(),
            label: "GitHub".into(),
            enabled: true,
            source: McpServerSource::Catalog {
                entry_id: "github".into(),
            },
            secrets: BTreeMap::from([("token".into(), "ghp_x".into())]),
            stored_secrets: None,
            tool_enabled: BTreeMap::new(),
            proxy_use: crate::proxy::ProxyUse::Auto,
            setup_complete: true,
            addon_projects: Vec::new(),
        }
    }

    #[tokio::test]
    async fn stored_secrets_are_read_back_at_the_point_of_use() {
        crate::secrets::seed_for_test(
            "mcp:11111111-1111-1111-1111-111111111111:token",
            "ghp_stored",
        );
        let mut config = catalog_server();
        config.secrets = BTreeMap::from([("token".into(), String::new())]);
        config.stored_secrets = Some(vec!["token".into()]);
        let resolved = config.resolved().await.unwrap();
        assert_eq!(resolved.secrets["token"], "ghp_stored");
        // The config the webview holds is untouched.
        assert_eq!(config.secrets["token"], "");
    }

    #[test]
    fn debug_names_secrets_but_never_prints_them() {
        let shown = format!("{:?}", catalog_server());
        assert!(!shown.contains("ghp_x"), "{shown}");
        assert!(shown.contains("\"token\": \"<redacted>\""), "{shown}");
    }

    #[test]
    fn a_server_is_only_startable_once_setup_finished() {
        let mut server = catalog_server();
        assert!(server.is_startable());

        server.setup_complete = false;
        assert!(
            !server.is_startable(),
            "a half-configured server would fail at spawn with a missing credential"
        );

        server.setup_complete = true;
        server.enabled = false;
        assert!(!server.is_startable());
    }

    #[test]
    fn an_older_settings_blob_without_the_new_maps_still_loads() {
        // Every map and flag added since the first release has a serde default,
        // so a user upgrading does not lose their servers to a parse failure.
        let stored = serde_json::json!({
            "id": "abc",
            "label": "GitHub",
            "enabled": true,
            "source": { "kind": "catalog", "entryId": "github" }
        });
        let parsed: McpServerConfig = serde_json::from_value(stored).unwrap();
        assert!(parsed.secrets.is_empty());
        assert!(parsed.tool_enabled.is_empty());
        assert!(
            !parsed.setup_complete,
            "an unknown setup state must read as incomplete, not as ready to run"
        );
    }

    #[test]
    fn a_server_follows_the_app_proxy_setting_by_default() {
        // The default has to be the one that needs no thought: the app setting
        // already declines to proxy loopback, so most servers never need the
        // override at all.
        assert_eq!(catalog_server().proxy_use, crate::proxy::ProxyUse::Auto);
    }

    #[test]
    fn an_older_settings_blob_predating_the_override_reads_as_auto() {
        let stored = serde_json::json!({
            "id": "abc",
            "label": "GitHub",
            "enabled": true,
            "source": { "kind": "catalog", "entryId": "github" }
        });
        let parsed: McpServerConfig = serde_json::from_value(stored).unwrap();
        assert_eq!(parsed.proxy_use, crate::proxy::ProxyUse::Auto);
    }

    #[test]
    fn a_remote_server_carries_its_url_and_token() {
        let remote = McpServerConfig {
            source: McpServerSource::Remote {
                url: "https://mcp.example.test/mcp".into(),
            },
            secrets: BTreeMap::from([(REMOTE_TOKEN_KEY.to_string(), "abc".to_string())]),
            ..catalog_server()
        };
        assert_eq!(remote.remote_url(), Some("https://mcp.example.test/mcp"));
        assert_eq!(remote.remote_token(), Some("abc"));
    }

    #[test]
    fn a_local_server_has_no_remote_url() {
        // The caller branches on this, so a stdio server answering with a URL
        // would send it down the HTTP path with nothing to connect to.
        assert_eq!(catalog_server().remote_url(), None);
    }

    #[test]
    fn the_source_tag_round_trips_through_the_ipc_shape() {
        let server = catalog_server();
        let json = serde_json::to_value(&server).unwrap();
        assert_eq!(json["source"]["kind"], "catalog");
        assert_eq!(json["source"]["entryId"], "github");
        assert_eq!(
            serde_json::from_value::<McpServerConfig>(json).unwrap(),
            server
        );
    }
}
