//! One configured MCP server, as stored in settings.
//!
//! Mirrors `EmailAccount`'s conventions deliberately: a frontend-generated UUID
//! as the stable key, a human label, a per-server `enabled` toggle, and
//! camelCase serde so one object round-trips through `invoke` untranslated.
//! Anything that reads as "how is this different from an email account" should
//! have an answer, and mostly does not.
//!
//! # Secrets
//!
//! Secrets collected during guided setup live in this struct, and therefore in
//! the settings blob — the same trust level as the existing Brave key, the
//! remote-inference key and IMAP passwords. That is a deliberate consistency
//! choice, not an oversight. Moving credentials to the OS keyring is worth
//! doing, but it is a cross-cutting change for *all* of them at once; adding a
//! second storage location for one integration would make that migration
//! harder, not easier. `email/auth.rs` says the same thing about the same
//! decision.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// How a configured server came to exist.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ts_rs::TS)]
#[ts(export)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum McpServerSource {
    /// Installed from the bundled catalog. `entryId` is the catalog entry's id,
    /// which is what lets a later app version notice a version bump.
    #[serde(rename_all = "camelCase")]
    Catalog { entry_id: String },
    /// Tier 3: the user supplied a command directly. No catalog entry, no
    /// guided setup, and the same approval rules — a hand-configured server is
    /// not more trusted than a curated one.
    #[serde(rename_all = "camelCase")]
    Custom {
        program: String,
        #[serde(default)]
        args: Vec<String>,
    },
}

/// A server the user has added.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ts_rs::TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct McpServerConfig {
    /// Stable UUID, generated by the frontend when the user adds the server.
    /// Used as the lookup key so relabelling does not break a running session
    /// or an in-flight tool reference.
    pub id: String,

    /// Human-facing label. Defaults to the catalog entry's name, but the user
    /// can have two GitHub servers for two accounts.
    pub label: String,

    /// Master per-server toggle. When false the server is not started and its
    /// tools do not reach the agent.
    pub enabled: bool,

    pub source: McpServerSource,

    /// Secrets collected during guided setup, keyed by the step's `key`. A
    /// catalog entry's `env` refers to these as `$secret.<key>`.
    #[serde(default)]
    pub secrets: BTreeMap<String, String>,

    /// Per-tool enablement, keyed by the tool's own name. A tool absent from
    /// this map has never been decided on and falls back to the catalog
    /// entry's tested `defaultTools`; Phase 05 owns that resolution.
    #[serde(default)]
    pub tool_enabled: BTreeMap<String, bool>,

    /// Whether the guided setup ran to completion. A server whose setup was
    /// abandoned halfway is configured but not startable, and the UI has to be
    /// able to say which.
    #[serde(default)]
    pub setup_complete: bool,
}

impl McpServerConfig {
    /// Whether this server should be started: enabled, and finished being set
    /// up. Custom servers have no setup steps, so they are complete by
    /// construction — but the flag is still what decides, so the two paths
    /// share one rule.
    pub fn is_startable(&self) -> bool {
        self.enabled && self.setup_complete
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn catalog_server() -> McpServerConfig {
        McpServerConfig {
            id: "11111111-1111-1111-1111-111111111111".into(),
            label: "GitHub".into(),
            enabled: true,
            source: McpServerSource::Catalog {
                entry_id: "github".into(),
            },
            secrets: BTreeMap::from([("token".into(), "ghp_x".into())]),
            tool_enabled: BTreeMap::new(),
            setup_complete: true,
        }
    }

    #[test]
    fn a_server_is_only_startable_once_setup_finished() {
        let mut server = catalog_server();
        assert!(server.is_startable());

        server.setup_complete = false;
        assert!(
            !server.is_startable(),
            "a half-configured server would fail at spawn with a missing credential"
        );

        server.setup_complete = true;
        server.enabled = false;
        assert!(!server.is_startable());
    }

    #[test]
    fn an_older_settings_blob_without_the_new_maps_still_loads() {
        // Every map and flag added since the first release has a serde default,
        // so a user upgrading does not lose their servers to a parse failure.
        let stored = serde_json::json!({
            "id": "abc",
            "label": "GitHub",
            "enabled": true,
            "source": { "kind": "catalog", "entryId": "github" }
        });
        let parsed: McpServerConfig = serde_json::from_value(stored).unwrap();
        assert!(parsed.secrets.is_empty());
        assert!(parsed.tool_enabled.is_empty());
        assert!(
            !parsed.setup_complete,
            "an unknown setup state must read as incomplete, not as ready to run"
        );
    }

    #[test]
    fn the_source_tag_round_trips_through_the_ipc_shape() {
        let server = catalog_server();
        let json = serde_json::to_value(&server).unwrap();
        assert_eq!(json["source"]["kind"], "catalog");
        assert_eq!(json["source"]["entryId"], "github");
        assert_eq!(
            serde_json::from_value::<McpServerConfig>(json).unwrap(),
            server
        );
    }
}
