//! The HTTP surface: bind a port, check the token, accept prompts, stream
//! answers back over SSE.
//!
//! SSE rather than WebSockets. Once a turn starts the traffic is one
//! directional, every browser speaks it without ceremony, and it survives
//! middleboxes that eat upgrades. Cancellation is a separate POST rather than
//! a reason to build a duplex channel.

use std::convert::Infallible;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::sync::Arc;
use std::time::Duration;

use axum::extract::{Path, State};
use axum::http::{HeaderMap, StatusCode, Uri};
use axum::response::sse::{Event, KeepAlive, Sse};
use axum::response::{Html, IntoResponse, Response};
use axum::routing::{get, post};
use axum::{Json, Router};
use futures_util::stream::Stream;
use serde::{Deserialize, Serialize};
use tokio::sync::{broadcast, watch};

use super::auth;
use super::relay::{PromptRequest, Relay, RelayError, RemoteEvent};

/// How often orphaned sessions are swept. Cheap: a map walk over at most
/// [`super::relay::MAX_SESSIONS`] entries.
const REAP_INTERVAL: Duration = Duration::from_secs(15);

/// Longest prompt a remote client may send. Generous for a chat box, small
/// enough that a paste bomb is not a memory event.
const MAX_MESSAGE_BYTES: usize = 32 * 1024;

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RemoteConfig {
    pub port: u16,
    /// Generated by the frontend (Web Crypto) and stored in settings. Rust
    /// never mints it, so rotation is a settings change and not an IPC dance.
    pub token: String,
    /// Bind `0.0.0.0` rather than loopback. False is useful for testing the
    /// server without exposing anything to the network.
    pub bind_all: bool,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RemoteStatus {
    pub running: bool,
    pub port: Option<u16>,
    pub bind_all: bool,
    pub sessions: usize,
}

/// Where an accepted prompt goes next.
///
/// In the app this is a Tauri event to the webview, which is the only thing
/// that can actually run a turn. Behind a trait because the HTTP surface is
/// worth testing end to end — token handling especially — and standing up an
/// `AppHandle` to do it is not realistic.
pub trait PromptSink: Send + Sync + 'static {
    /// Hand a prompt to whoever runs turns. An error means nobody is
    /// listening, and the caller fails the turn rather than leaving the client
    /// waiting on an answer that will never come.
    fn dispatch(&self, request: PromptRequest) -> Result<(), String>;
    fn cancel(&self, turn_id: &str);
}

#[derive(Clone)]
struct AppState {
    sink: Arc<dyn PromptSink>,
    relay: Arc<Relay>,
    token: Arc<String>,
}

pub struct Running {
    pub port: u16,
    pub bind_all: bool,
    pub token: String,
    shutdown: watch::Sender<bool>,
}

impl Running {
    pub fn stop(&self) {
        let _ = self.shutdown.send(true);
    }
}

/// Bind and serve. Returns once the socket is listening, so a caller that gets
/// `Ok` can hand out the link immediately.
pub async fn start(
    sink: Arc<dyn PromptSink>,
    relay: Arc<Relay>,
    config: RemoteConfig,
) -> Result<Running, String> {
    if config.token.trim().is_empty() {
        return Err("refusing to start without an access token".into());
    }

    let host = if config.bind_all {
        IpAddr::V4(Ipv4Addr::UNSPECIFIED)
    } else {
        IpAddr::V4(Ipv4Addr::LOCALHOST)
    };
    let addr = SocketAddr::new(host, config.port);

    let listener = tokio::net::TcpListener::bind(addr).await.map_err(|e| {
        format!("could not listen on {addr}: {e} — another program may already have that port")
    })?;
    let port = listener
        .local_addr()
        .map(|a| a.port())
        .unwrap_or(config.port);

    let state = AppState {
        sink: sink.clone(),
        relay: relay.clone(),
        token: Arc::new(config.token.clone()),
    };

    let router = Router::new()
        .route("/", get(index))
        .route("/api/health", get(health))
        .route("/api/chat", post(chat))
        .route("/api/cancel", post(cancel))
        .route("/api/stream/{session}", get(stream))
        .with_state(state);

    let (shutdown, mut shutdown_rx) = watch::channel(false);

    let mut serve_rx = shutdown.subscribe();
    tokio::spawn(async move {
        let served = axum::serve(listener, router).with_graceful_shutdown(async move {
            let _ = serve_rx.wait_for(|stop| *stop).await;
        });
        if let Err(e) = served.await {
            log::error!("[remote] server stopped: {e}");
        }
    });

    // Orphan sweep: a client that closed its tab mid-answer must not hold an
    // inference slot until the app restarts.
    let reap_sink = sink.clone();
    let reap_relay = relay.clone();
    tokio::spawn(async move {
        loop {
            tokio::select! {
                _ = tokio::time::sleep(REAP_INTERVAL) => {}
                _ = shutdown_rx.wait_for(|stop| *stop) => break,
            }
            for turn_id in reap_relay.reap() {
                log::info!("[remote] abandoning turn {turn_id}: nobody is listening");
                reap_sink.cancel(&turn_id);
            }
        }
    });

    log::info!(
        "[remote] serving on {}:{port}",
        if config.bind_all {
            "0.0.0.0"
        } else {
            "127.0.0.1"
        }
    );

    Ok(Running {
        port,
        bind_all: config.bind_all,
        token: config.token,
        shutdown,
    })
}

// --- handlers --------------------------------------------------------------

/// `None` when the caller is authorised; otherwise the response to send back
/// instead of handling the request.
fn unauthorised(state: &AppState, headers: &HeaderMap, uri: &Uri) -> Option<Response> {
    let provided = auth::extract_token(headers, uri.query()).unwrap_or_default();
    if auth::token_matches(&state.token, &provided) {
        None
    } else {
        Some((StatusCode::UNAUTHORIZED, "not for you").into_response())
    }
}

/// Unauthenticated on purpose: the host's own settings page uses this to say
/// whether the server is actually up, and it reveals nothing but that.
async fn health() -> impl IntoResponse {
    Json(serde_json::json!({ "ok": true, "service": "haruspex" }))
}

/// Phase 02 replaces this with the real client. Until then it is a stub that
/// proves the token path end to end.
async fn index(State(state): State<AppState>, headers: HeaderMap, uri: Uri) -> Response {
    if unauthorised(&state, &headers, &uri).is_some() {
        // Deliberately says nothing about what is running here.
        return Html(NO_TOKEN_PAGE).into_response();
    }
    Html(PLACEHOLDER_PAGE).into_response()
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ChatRequest {
    session_id: String,
    message: String,
}

async fn chat(
    State(state): State<AppState>,
    headers: HeaderMap,
    uri: Uri,
    Json(body): Json<ChatRequest>,
) -> Response {
    if let Some(response) = unauthorised(&state, &headers, &uri) {
        return response;
    }
    let message = body.message.trim().to_string();
    if message.is_empty() {
        return (StatusCode::BAD_REQUEST, "empty message").into_response();
    }
    if message.len() > MAX_MESSAGE_BYTES {
        return (StatusCode::PAYLOAD_TOO_LARGE, "message too long").into_response();
    }

    match state.relay.begin_turn(&body.session_id, message) {
        Ok(request) => {
            let turn_id = request.turn_id.clone();
            // The frontend is the only thing that can run a turn; if the
            // handoff fails there is nobody to answer, so the turn is failed
            // rather than left waiting forever.
            if let Err(e) = state.sink.dispatch(request) {
                let _ = state
                    .relay
                    .fail(&turn_id, "the desktop app is not listening".into());
                log::error!("[remote] could not hand off prompt: {e}");
                return (
                    StatusCode::SERVICE_UNAVAILABLE,
                    "the desktop app is not ready",
                )
                    .into_response();
            }
            (
                StatusCode::ACCEPTED,
                Json(serde_json::json!({ "turnId": turn_id })),
            )
                .into_response()
        }
        Err(e) => relay_error_response(e),
    }
}

fn relay_error_response(error: RelayError) -> Response {
    let status = match error {
        RelayError::Busy => StatusCode::CONFLICT,
        RelayError::TooManySessions => StatusCode::SERVICE_UNAVAILABLE,
        RelayError::RateLimited => StatusCode::TOO_MANY_REQUESTS,
        RelayError::BadSessionId => StatusCode::BAD_REQUEST,
        RelayError::UnknownTurn => StatusCode::NOT_FOUND,
    };
    (status, error.message()).into_response()
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CancelRequest {
    session_id: String,
}

async fn cancel(
    State(state): State<AppState>,
    headers: HeaderMap,
    uri: Uri,
    Json(body): Json<CancelRequest>,
) -> Response {
    if let Some(response) = unauthorised(&state, &headers, &uri) {
        return response;
    }
    match state.relay.in_flight_turn(&body.session_id) {
        Some(turn_id) => {
            state.sink.cancel(&turn_id);
            StatusCode::ACCEPTED.into_response()
        }
        // Nothing to stop is a success: the client wanted no turn running, and
        // there is no turn running.
        None => StatusCode::NO_CONTENT.into_response(),
    }
}

async fn stream(
    State(state): State<AppState>,
    Path(session_id): Path<String>,
    headers: HeaderMap,
    uri: Uri,
) -> Response {
    if let Some(response) = unauthorised(&state, &headers, &uri) {
        return response;
    }
    let (rx, snapshot) = match state.relay.subscribe(&session_id) {
        Ok(pair) => pair,
        Err(e) => return relay_error_response(e),
    };

    let guard = SubscriberGuard {
        relay: state.relay.clone(),
        session_id: session_id.clone(),
    };
    let stream = event_stream(rx, snapshot, guard);

    Sse::new(stream)
        .keep_alive(KeepAlive::new().interval(Duration::from_secs(15)))
        .into_response()
}

/// Drops the session's subscriber count when the SSE stream ends, however it
/// ends. Without this a closed tab would look like a listener forever and its
/// turn would never be reaped.
struct SubscriberGuard {
    relay: Arc<Relay>,
    session_id: String,
}

impl Drop for SubscriberGuard {
    fn drop(&mut self) {
        self.relay.unsubscribe(&self.session_id);
    }
}

struct StreamState {
    rx: broadcast::Receiver<RemoteEvent>,
    guard: SubscriberGuard,
    /// The snapshot to send before anything else, so a reconnecting client is
    /// in sync from its first frame.
    pending: Option<RemoteEvent>,
}

fn event_stream(
    rx: broadcast::Receiver<RemoteEvent>,
    snapshot: RemoteEvent,
    guard: SubscriberGuard,
) -> impl Stream<Item = Result<Event, Infallible>> {
    let state = StreamState {
        rx,
        guard,
        pending: Some(snapshot),
    };
    futures_util::stream::unfold(state, |mut state| async move {
        loop {
            if let Some(event) = state.pending.take() {
                return Some((Ok(sse_event(&event)), state));
            }
            match state.rx.recv().await {
                Ok(event) => return Some((Ok(sse_event(&event)), state)),
                // A slow reader missed deltas. Deltas are suffixes, so the gap
                // cannot be papered over — resend the whole buffer instead.
                Err(broadcast::error::RecvError::Lagged(_)) => {
                    state.pending = state.guard.relay.snapshot(&state.guard.session_id);
                    // No snapshot means the session is gone; the stream ends
                    // rather than spinning on a receiver nobody will feed.
                    state.pending.as_ref()?;
                }
                Err(broadcast::error::RecvError::Closed) => return None,
            }
        }
    })
}

fn sse_event(event: &RemoteEvent) -> Event {
    match Event::default().json_data(event) {
        Ok(e) => e,
        // Serialising our own enum cannot realistically fail, but a stream that
        // dies on it would be a mystery; a visible error frame is not.
        Err(e) => Event::default().data(format!(r#"{{"type":"error","message":"{e}"}}"#)),
    }
}

const NO_TOKEN_PAGE: &str = r#"<!doctype html>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Haruspex</title>
<style>body{font:16px/1.5 system-ui,sans-serif;max-width:32rem;margin:20vh auto;padding:0 1.5rem;color:#222}</style>
<h1>You need a link</h1>
<p>This page only opens with the link its host shared with you — the whole link,
including the part after the question mark.</p>
"#;

const PLACEHOLDER_PAGE: &str = r#"<!doctype html>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Haruspex</title>
<style>body{font:16px/1.5 system-ui,sans-serif;max-width:32rem;margin:20vh auto;padding:0 1.5rem;color:#222}code{background:#eee;padding:0 4px}</style>
<h1>Connected</h1>
<p>Your link works. The chat client itself lands in the next phase; until then
this page exists to prove the token and the server are wired up.</p>
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_blank_token_is_refused_before_binding() {
        // Guards the case where the server is enabled before a token exists:
        // binding first and validating later would put an open port on the LAN.
        let config = RemoteConfig {
            port: 0,
            token: "   ".into(),
            bind_all: false,
        };
        assert!(config.token.trim().is_empty());
    }

    #[test]
    fn relay_errors_map_to_distinguishable_statuses() {
        let status = |e: RelayError| relay_error_response(e).status();
        assert_eq!(status(RelayError::Busy), StatusCode::CONFLICT);
        assert_eq!(
            status(RelayError::RateLimited),
            StatusCode::TOO_MANY_REQUESTS
        );
        assert_eq!(
            status(RelayError::TooManySessions),
            StatusCode::SERVICE_UNAVAILABLE
        );
        assert_eq!(status(RelayError::BadSessionId), StatusCode::BAD_REQUEST);
    }
}

#[cfg(test)]
mod http_tests {
    //! End-to-end over a real socket. The token path in particular is worth
    //! exercising as a client sees it rather than as a unit test of the
    //! comparison function — every interesting mistake here is a route wired up
    //! without the check, not a broken comparison.

    use super::*;
    use std::sync::Mutex as StdMutex;

    #[derive(Default)]
    struct RecordingSink {
        dispatched: StdMutex<Vec<PromptRequest>>,
        cancelled: StdMutex<Vec<String>>,
        fail_dispatch: bool,
    }

    impl PromptSink for RecordingSink {
        fn dispatch(&self, request: PromptRequest) -> Result<(), String> {
            if self.fail_dispatch {
                return Err("no webview".into());
            }
            self.dispatched.lock().unwrap().push(request);
            Ok(())
        }

        fn cancel(&self, turn_id: &str) {
            self.cancelled.lock().unwrap().push(turn_id.to_string());
        }
    }

    const TOKEN: &str = "test-token";

    async fn serve(sink: Arc<RecordingSink>) -> (String, Arc<Relay>, Running) {
        let relay = Arc::new(Relay::new());
        let running = start(
            sink,
            relay.clone(),
            RemoteConfig {
                // Port 0: the OS picks a free one, so tests never collide with
                // each other or with a real Haruspex on the dev box.
                port: 0,
                token: TOKEN.into(),
                bind_all: false,
            },
        )
        .await
        .expect("server should bind");
        let base = format!("http://127.0.0.1:{}", running.port);
        (base, relay, running)
    }

    #[tokio::test]
    async fn health_needs_no_token_but_the_rest_does() {
        let sink = Arc::new(RecordingSink::default());
        let (base, _relay, running) = serve(sink.clone()).await;
        let client = reqwest::Client::new();

        assert_eq!(
            client
                .get(format!("{base}/api/health"))
                .send()
                .await
                .unwrap()
                .status(),
            200
        );

        // Every authenticated route, with no token and with a wrong one.
        for token in ["", "wrong-token"] {
            let suffix = if token.is_empty() {
                String::new()
            } else {
                format!("?t={token}")
            };
            let chat = client
                .post(format!("{base}/api/chat{suffix}"))
                .json(&serde_json::json!({ "sessionId": "s1", "message": "hi" }))
                .send()
                .await
                .unwrap();
            assert_eq!(chat.status(), 401, "chat accepted token {token:?}");

            let stream = client
                .get(format!("{base}/api/stream/s1{suffix}"))
                .send()
                .await
                .unwrap();
            assert_eq!(stream.status(), 401, "stream accepted token {token:?}");

            let cancel = client
                .post(format!("{base}/api/cancel{suffix}"))
                .json(&serde_json::json!({ "sessionId": "s1" }))
                .send()
                .await
                .unwrap();
            assert_eq!(cancel.status(), 401, "cancel accepted token {token:?}");
        }

        assert!(sink.dispatched.lock().unwrap().is_empty());
        running.stop();
    }

    #[tokio::test]
    async fn an_unauthenticated_visitor_gets_no_chat_box_and_no_information() {
        let (base, _relay, running) = serve(Arc::new(RecordingSink::default())).await;
        let body = reqwest::get(&base).await.unwrap().text().await.unwrap();
        assert!(body.contains("You need a link"));
        // Says nothing about what is running here, what model, or who owns it.
        assert!(!body.to_lowercase().contains("connected"));
        running.stop();
    }

    #[tokio::test]
    async fn a_prompt_reaches_the_sink_and_streams_back() {
        let sink = Arc::new(RecordingSink::default());
        let (base, relay, running) = serve(sink.clone()).await;
        let client = reqwest::Client::new();

        let mut stream = client
            .get(format!("{base}/api/stream/s1?t={TOKEN}"))
            .send()
            .await
            .unwrap();
        assert_eq!(stream.status(), 200);
        // First frame is always a snapshot, so a client is in sync before it
        // has seen a single delta.
        let first = String::from_utf8_lossy(&stream.chunk().await.unwrap().unwrap()).to_string();
        assert!(first.contains("\"type\":\"snapshot\""), "got {first}");

        let accepted = client
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "what is a haruspex?" }))
            .send()
            .await
            .unwrap();
        assert_eq!(accepted.status(), 202);

        let dispatched = sink.dispatched.lock().unwrap().clone();
        assert_eq!(dispatched.len(), 1);
        assert_eq!(dispatched[0].message, "what is a haruspex?");
        assert_eq!(dispatched[0].session_id, "s1");

        // Now play the part of the frontend driver.
        relay
            .push_text(&dispatched[0].turn_id, "a reader of")
            .unwrap();
        relay
            .finish(&dispatched[0].turn_id, "a reader of entrails".into())
            .unwrap();

        let mut seen = String::new();
        while !seen.contains("\"type\":\"done\"") {
            match stream.chunk().await.unwrap() {
                Some(bytes) => seen.push_str(&String::from_utf8_lossy(&bytes)),
                None => panic!("stream ended before the answer: {seen}"),
            }
        }
        assert!(seen.contains("a reader of"), "no delta in {seen}");
        assert!(seen.contains("entrails"), "no final text in {seen}");
        running.stop();
    }

    #[tokio::test]
    async fn a_prompt_nobody_can_run_fails_instead_of_hanging() {
        let sink = Arc::new(RecordingSink {
            fail_dispatch: true,
            ..Default::default()
        });
        let (base, relay, running) = serve(sink).await;
        let response = reqwest::Client::new()
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "hi" }))
            .send()
            .await
            .unwrap();
        assert_eq!(response.status(), 503);
        // And the turn is not left sitting in the relay marked as in flight.
        assert_eq!(relay.in_flight_turn("s1"), None);
        running.stop();
    }

    #[tokio::test]
    async fn cancel_reaches_the_sink_only_when_there_is_something_to_stop() {
        let sink = Arc::new(RecordingSink::default());
        let (base, _relay, running) = serve(sink.clone()).await;
        let client = reqwest::Client::new();

        let idle = client
            .post(format!("{base}/api/cancel?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1" }))
            .send()
            .await
            .unwrap();
        assert_eq!(idle.status(), 204);
        assert!(sink.cancelled.lock().unwrap().is_empty());

        client
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "hi" }))
            .send()
            .await
            .unwrap();
        let busy = client
            .post(format!("{base}/api/cancel?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1" }))
            .send()
            .await
            .unwrap();
        assert_eq!(busy.status(), 202);
        assert_eq!(sink.cancelled.lock().unwrap().len(), 1);
        running.stop();
    }

    #[tokio::test]
    async fn oversized_and_empty_prompts_are_refused() {
        let (base, _relay, running) = serve(Arc::new(RecordingSink::default())).await;
        let client = reqwest::Client::new();

        let empty = client
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "   " }))
            .send()
            .await
            .unwrap();
        assert_eq!(empty.status(), 400);

        let huge = client
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({
                "sessionId": "s1",
                "message": "x".repeat(MAX_MESSAGE_BYTES + 1)
            }))
            .send()
            .await
            .unwrap();
        assert_eq!(huge.status(), 413);
        running.stop();
    }

    #[tokio::test]
    async fn a_stopped_server_stops_answering() {
        let (base, _relay, running) = serve(Arc::new(RecordingSink::default())).await;
        assert!(reqwest::get(format!("{base}/api/health")).await.is_ok());
        running.stop();

        // Graceful shutdown is not instant; poll rather than sleep-and-hope.
        for _ in 0..50 {
            if reqwest::get(format!("{base}/api/health")).await.is_err() {
                return;
            }
            tokio::time::sleep(Duration::from_millis(20)).await;
        }
        panic!("server still answering after stop");
    }
}
