//! The HTTP surface: bind a port, check the token, accept prompts, stream
//! answers back over SSE.
//!
//! SSE rather than WebSockets. Once a turn starts the traffic is one
//! directional, every browser speaks it without ceremony, and it survives
//! middleboxes that eat upgrades. Cancellation is a separate POST rather than
//! a reason to build a duplex channel.

use std::convert::Infallible;
use std::future::Future;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::pin::Pin;
use std::sync::Arc;
use std::time::Duration;

use axum::extract::{Path, State};
use axum::http::header::{CACHE_CONTROL, CONTENT_TYPE, SET_COOKIE};
use axum::http::{HeaderMap, StatusCode, Uri};
use axum::response::sse::{Event, KeepAlive, Sse};
use axum::response::{Html, IntoResponse, Response};
use axum::routing::{get, post};
use axum::{Json, Router};
use futures_util::stream::Stream;
use serde::{Deserialize, Serialize};
use tokio::sync::{broadcast, watch};

use super::auth;
use super::relay::{Answer, PromptRequest, Relay, RelayError, RemoteEvent};

/// How often orphaned sessions are swept. Cheap: a map walk over at most
/// [`super::relay::MAX_SESSIONS`] entries.
const REAP_INTERVAL: Duration = Duration::from_secs(15);

/// Longest prompt a remote client may send. Generous for a chat box, small
/// enough that a paste bomb is not a memory event.
const MAX_MESSAGE_BYTES: usize = 32 * 1024;

/// Longest answer read aloud in one request — around four minutes of speech.
const MAX_SPEECH_CHARS: usize = 4000;

/// The TTS sidecar's port, and the app's default voice. Kept local rather than
/// threaded through the config so that changing the host's voice in Settings
/// cannot restart the server and drop a guest mid-answer.
const TTS_PORT: u16 = 3001;
const DEFAULT_VOICE: &str = "af_heart";

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RemoteConfig {
    pub port: u16,
    /// Generated by the frontend (Web Crypto) and stored in settings. Rust
    /// never mints it, so rotation is a settings change and not an IPC dance.
    pub token: String,
    /// Bind `0.0.0.0` rather than loopback. False is useful for testing the
    /// server without exposing anything to the network.
    pub bind_all: bool,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RemoteStatus {
    pub running: bool,
    pub port: Option<u16>,
    pub bind_all: bool,
    pub sessions: usize,
}

/// Everything the HTTP layer needs from the app it is embedded in.
///
/// Behind a trait because the HTTP surface is worth testing end to end — token
/// handling especially — and standing up an `AppHandle` to do it is not
/// realistic.
pub trait Host: Send + Sync + 'static {
    /// Hand a prompt to whoever runs turns — in the app, a Tauri event to the
    /// webview, which is the only thing that can run one. An error means nobody
    /// is listening, and the caller fails the turn rather than leaving the
    /// client waiting on an answer that will never come.
    fn dispatch(&self, request: PromptRequest) -> Result<(), String>;

    fn cancel(&self, turn_id: &str);

    /// Make sure the speech sidecar is running, starting it if not.
    ///
    /// The app starts koko lazily — the host's own Listen button starts it on
    /// first use — so a guest tapping Listen on a machine whose owner has not
    /// used speech this session finds nothing listening on the port.
    fn ensure_speech(&self) -> BoxFuture<Result<(), String>>;

    /// Deliver a guest's answer to the turn that is parked on the question.
    fn answer(&self, turn_id: &str, answer: &Answer);
}

/// A boxed future, because [`Host`] is a trait object and this crate has no
/// async-trait dependency.
pub type BoxFuture<T> = Pin<Box<dyn Future<Output = T> + Send>>;

#[derive(Clone)]
struct AppState {
    host: Arc<dyn Host>,
    relay: Arc<Relay>,
    token: Arc<String>,
}

pub struct Running {
    pub port: u16,
    pub bind_all: bool,
    pub token: String,
    shutdown: watch::Sender<bool>,
}

impl Running {
    pub fn stop(&self) {
        let _ = self.shutdown.send(true);
    }
}

/// Bind and serve. Returns once the socket is listening, so a caller that gets
/// `Ok` can hand out the link immediately.
pub async fn start(
    host: Arc<dyn Host>,
    relay: Arc<Relay>,
    config: RemoteConfig,
) -> Result<Running, String> {
    if config.token.trim().is_empty() {
        return Err("refusing to start without an access token".into());
    }

    let bind_ip = if config.bind_all {
        IpAddr::V4(Ipv4Addr::UNSPECIFIED)
    } else {
        IpAddr::V4(Ipv4Addr::LOCALHOST)
    };
    let addr = SocketAddr::new(bind_ip, config.port);

    let listener = tokio::net::TcpListener::bind(addr).await.map_err(|e| {
        format!("could not listen on {addr}: {e} — another program may already have that port")
    })?;
    let port = listener
        .local_addr()
        .map(|a| a.port())
        .unwrap_or(config.port);

    let state = AppState {
        host: host.clone(),
        relay: relay.clone(),
        token: Arc::new(config.token.clone()),
    };

    let router = Router::new()
        .route("/", get(index))
        .route("/app.css", get(stylesheet))
        .route("/app.js", get(script))
        .route("/api/health", get(health))
        .route("/api/chat", post(chat))
        .route("/api/cancel", post(cancel))
        .route("/api/answer", post(answer))
        .route("/api/speak", post(speak))
        .route("/api/stream/{session}", get(stream))
        .with_state(state);

    let (shutdown, mut shutdown_rx) = watch::channel(false);

    let mut serve_rx = shutdown.subscribe();
    tokio::spawn(async move {
        let served = axum::serve(listener, router).with_graceful_shutdown(async move {
            let _ = serve_rx.wait_for(|stop| *stop).await;
        });
        if let Err(e) = served.await {
            log::error!("[remote] server stopped: {e}");
        }
    });

    // Orphan sweep: a client that closed its tab mid-answer must not hold an
    // inference slot until the app restarts.
    let reap_host = host.clone();
    let reap_relay = relay.clone();
    tokio::spawn(async move {
        loop {
            tokio::select! {
                _ = tokio::time::sleep(REAP_INTERVAL) => {}
                _ = shutdown_rx.wait_for(|stop| *stop) => break,
            }
            for turn_id in reap_relay.reap() {
                log::info!("[remote] abandoning turn {turn_id}: nobody is listening");
                reap_host.cancel(&turn_id);
            }
        }
    });

    log::info!(
        "[remote] serving on {}:{port}",
        if config.bind_all {
            "0.0.0.0"
        } else {
            "127.0.0.1"
        }
    );

    Ok(Running {
        port,
        bind_all: config.bind_all,
        token: config.token,
        shutdown,
    })
}

// --- handlers --------------------------------------------------------------

/// `None` when the caller is authorised; otherwise the response to send back
/// instead of handling the request.
fn unauthorised(state: &AppState, headers: &HeaderMap, uri: &Uri) -> Option<Response> {
    let provided = auth::extract_token(headers, uri.query()).unwrap_or_default();
    if auth::token_matches(&state.token, &provided) {
        None
    } else {
        Some((StatusCode::UNAUTHORIZED, "not for you").into_response())
    }
}

/// Unauthenticated on purpose: the host's own settings page uses this to say
/// whether the server is actually up, and it reveals nothing but that.
async fn health() -> impl IntoResponse {
    Json(serde_json::json!({ "ok": true, "service": "haruspex" }))
}

async fn index(State(state): State<AppState>, headers: HeaderMap, uri: Uri) -> Response {
    if unauthorised(&state, &headers, &uri).is_some() {
        // Deliberately says nothing about what is running here.
        return no_cache(Html(NO_TOKEN_PAGE).into_response());
    }
    let page = CLIENT_HTML.replace("{{host}}", &html_escape(&host_name()));
    let mut response = no_cache(Html(page).into_response());
    // So a guest who bookmarks the page, or adds it to their home screen
    // without the query string, is not locked out of their own link.
    if let Ok(cookie) = auth::token_cookie(&state.token).parse() {
        response.headers_mut().insert(SET_COOKIE, cookie);
    }
    response
}

/// The client's assets are unauthenticated on purpose: they are a static page
/// and a static script, identical for everyone, and gating them would only mean
/// a guest whose cookie lapsed sees an unstyled page instead of a clear error
/// from the API.
async fn stylesheet() -> Response {
    asset(CLIENT_CSS, "text/css; charset=utf-8")
}

async fn script() -> Response {
    asset(CLIENT_JS, "text/javascript; charset=utf-8")
}

fn asset(body: &'static str, content_type: &'static str) -> Response {
    let mut response = body.into_response();
    response
        .headers_mut()
        .insert(CONTENT_TYPE, content_type.parse().expect("static mime"));
    no_cache(response)
}

/// Never stored, not merely revalidated.
///
/// An app update changes these files, and a guest holding an older script that
/// talks to a newer API is a bug nobody will diagnose from the other end of a
/// phone call. `no-cache` asks the browser to revalidate, but these responses
/// carry no validator, and a phone's back-forward cache will happily keep a
/// whole page anyway — so the instruction is not to keep it at all.
fn no_cache(mut response: Response) -> Response {
    response.headers_mut().insert(
        CACHE_CONTROL,
        "no-store, must-revalidate".parse().expect("static header"),
    );
    response
}

/// Whose computer this is, for the notice on the page. Best effort by design —
/// the fallback still says something true.
fn host_name() -> String {
    std::env::var("COMPUTERNAME")
        .ok()
        .or_else(|| std::env::var("HOSTNAME").ok())
        .or_else(|| std::fs::read_to_string("/etc/hostname").ok())
        .map(|name| name.trim().to_string())
        .filter(|name| !name.is_empty())
        .unwrap_or_else(|| "this computer".to_string())
}

/// The hostname comes from the OS rather than from a request, but it is still
/// interpolated into a page, and "trusted enough" is how injection happens.
fn html_escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ChatRequest {
    session_id: String,
    message: String,
    /// What the guest calls themselves. Optional: a guest who skips the
    /// question still gets a conversation, just a generically named one.
    #[serde(default)]
    client_label: Option<String>,
}

async fn chat(
    State(state): State<AppState>,
    headers: HeaderMap,
    uri: Uri,
    Json(body): Json<ChatRequest>,
) -> Response {
    if let Some(response) = unauthorised(&state, &headers, &uri) {
        return response;
    }
    let message = body.message.trim().to_string();
    if message.is_empty() {
        return (StatusCode::BAD_REQUEST, "empty message").into_response();
    }
    if message.len() > MAX_MESSAGE_BYTES {
        return (StatusCode::PAYLOAD_TOO_LARGE, "message too long").into_response();
    }

    match state
        .relay
        .begin_turn(&body.session_id, message, body.client_label)
    {
        Ok(request) => {
            let turn_id = request.turn_id.clone();
            // The frontend is the only thing that can run a turn; if the
            // handoff fails there is nobody to answer, so the turn is failed
            // rather than left waiting forever.
            if let Err(e) = state.host.dispatch(request) {
                let _ = state
                    .relay
                    .fail(&turn_id, "the desktop app is not listening".into());
                log::error!("[remote] could not hand off prompt: {e}");
                return (
                    StatusCode::SERVICE_UNAVAILABLE,
                    "the desktop app is not ready",
                )
                    .into_response();
            }
            (
                StatusCode::ACCEPTED,
                Json(serde_json::json!({ "turnId": turn_id })),
            )
                .into_response()
        }
        Err(e) => relay_error_response(e),
    }
}

fn relay_error_response(error: RelayError) -> Response {
    let status = match error {
        RelayError::Busy => StatusCode::CONFLICT,
        RelayError::TooManySessions => StatusCode::SERVICE_UNAVAILABLE,
        RelayError::RateLimited => StatusCode::TOO_MANY_REQUESTS,
        RelayError::BadSessionId => StatusCode::BAD_REQUEST,
        RelayError::UnknownTurn => StatusCode::NOT_FOUND,
    };
    (status, error.message()).into_response()
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CancelRequest {
    session_id: String,
}

async fn cancel(
    State(state): State<AppState>,
    headers: HeaderMap,
    uri: Uri,
    Json(body): Json<CancelRequest>,
) -> Response {
    if let Some(response) = unauthorised(&state, &headers, &uri) {
        return response;
    }
    match state.relay.in_flight_turn(&body.session_id) {
        Some(turn_id) => {
            state.host.cancel(&turn_id);
            StatusCode::ACCEPTED.into_response()
        }
        // Nothing to stop is a success: the client wanted no turn running, and
        // there is no turn running.
        None => StatusCode::NO_CONTENT.into_response(),
    }
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AnswerRequest {
    session_id: String,
    #[serde(flatten)]
    answer: Answer,
}

/// The guest's reply to a question the model asked.
///
/// The turn is parked on it holding an inference slot, so this is the fastest
/// path in the file: validate, hand it to the driver, return.
async fn answer(
    State(state): State<AppState>,
    headers: HeaderMap,
    uri: Uri,
    Json(body): Json<AnswerRequest>,
) -> Response {
    if let Some(response) = unauthorised(&state, &headers, &uri) {
        return response;
    }
    match state.relay.answer(&body.session_id, &body.answer) {
        Ok(turn_id) => {
            state.host.answer(&turn_id, &body.answer);
            StatusCode::ACCEPTED.into_response()
        }
        // The question has already been answered or the turn moved on. Not an
        // error worth alarming a guest about — a double tap looks exactly like
        // this — but not something to deliver either.
        Err(_) => StatusCode::NO_CONTENT.into_response(),
    }
}

#[derive(Debug, Deserialize)]
struct SpeakRequest {
    text: String,
}

/// Reads an answer aloud, by relaying to the TTS sidecar the app already runs.
///
/// No synthesis happens here and no Tauri state is touched: koko listens on
/// loopback and speaks an OpenAI-compatible dialect, so this is a proxy with a
/// container swap. If the host has never turned TTS on, the sidecar is not
/// running and the guest gets a plain "not available" rather than a hang.
async fn speak(
    State(state): State<AppState>,
    headers: HeaderMap,
    uri: Uri,
    Json(body): Json<SpeakRequest>,
) -> Response {
    if let Some(response) = unauthorised(&state, &headers, &uri) {
        return response;
    }
    let text = body.text.trim();
    if text.is_empty() {
        return (StatusCode::BAD_REQUEST, "nothing to say").into_response();
    }
    // Long answers are truncated rather than refused: hearing the first part is
    // more useful than an error, and synthesising ten minutes of audio to serve
    // one tap is not.
    let text = crate::text_util::truncate_at_char_boundary(text, MAX_SPEECH_CHARS);

    // Start the sidecar if this is the first speech on this machine since
    // launch — which it usually is, since the host has their own ears and does
    // not need their own answers read aloud.
    if let Err(e) = state.host.ensure_speech().await {
        log::warn!("[remote] speech could not be started: {e}");
        return (
            StatusCode::SERVICE_UNAVAILABLE,
            "the host's speech engine could not start",
        )
            .into_response();
    }

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(120))
        .build();
    let Ok(client) = client else {
        return (
            StatusCode::INTERNAL_SERVER_ERROR,
            "could not build a client",
        )
            .into_response();
    };

    let response = client
        .post(format!("http://127.0.0.1:{TTS_PORT}/v1/audio/speech"))
        .json(&serde_json::json!({
            "model": "tts-1",
            "input": text,
            "voice": DEFAULT_VOICE,
            "response_format": "pcm"
        }))
        .send()
        .await;

    let audio = match response {
        Ok(response) if response.status().is_success() => response.bytes().await,
        Ok(response) => {
            log::warn!("[remote] speech failed: {}", response.status());
            return (StatusCode::BAD_GATEWAY, "speech is not available").into_response();
        }
        Err(e) => {
            // Started, and still unreachable: not something a guest can act on.
            log::warn!("[remote] speech unreachable: {e}");
            return (StatusCode::SERVICE_UNAVAILABLE, "speech is not available").into_response();
        }
    };
    let Ok(audio) = audio else {
        return (StatusCode::BAD_GATEWAY, "speech was cut off").into_response();
    };
    if audio.len() < 100 {
        return (StatusCode::BAD_GATEWAY, "speech produced no audio").into_response();
    }

    let mut response = wav_from_pcm(&audio).into_response();
    response
        .headers_mut()
        .insert(CONTENT_TYPE, "audio/wav".parse().expect("static mime"));
    no_cache(response)
}

/// Wrap koko's raw PCM in the 44-byte header a browser needs to play it.
///
/// The sidecar returns signed 16-bit mono at 24kHz — the same assumption the
/// desktop playback path makes — and `<audio>` will not touch headerless PCM.
fn wav_from_pcm(pcm: &[u8]) -> Vec<u8> {
    const CHANNELS: u16 = 1;
    const SAMPLE_RATE: u32 = 24_000;
    const BITS: u16 = 16;
    let byte_rate = SAMPLE_RATE * CHANNELS as u32 * (BITS / 8) as u32;
    let block_align = CHANNELS * (BITS / 8);
    let data_len = pcm.len() as u32;

    let mut out = Vec::with_capacity(44 + pcm.len());
    out.extend_from_slice(b"RIFF");
    out.extend_from_slice(&(36 + data_len).to_le_bytes());
    out.extend_from_slice(b"WAVEfmt ");
    out.extend_from_slice(&16u32.to_le_bytes()); // PCM header size
    out.extend_from_slice(&1u16.to_le_bytes()); // uncompressed
    out.extend_from_slice(&CHANNELS.to_le_bytes());
    out.extend_from_slice(&SAMPLE_RATE.to_le_bytes());
    out.extend_from_slice(&byte_rate.to_le_bytes());
    out.extend_from_slice(&block_align.to_le_bytes());
    out.extend_from_slice(&BITS.to_le_bytes());
    out.extend_from_slice(b"data");
    out.extend_from_slice(&data_len.to_le_bytes());
    out.extend_from_slice(pcm);
    out
}

async fn stream(
    State(state): State<AppState>,
    Path(session_id): Path<String>,
    headers: HeaderMap,
    uri: Uri,
) -> Response {
    if let Some(response) = unauthorised(&state, &headers, &uri) {
        return response;
    }
    let (rx, snapshot) = match state.relay.subscribe(&session_id) {
        Ok(pair) => pair,
        Err(e) => return relay_error_response(e),
    };

    let guard = SubscriberGuard {
        relay: state.relay.clone(),
        session_id: session_id.clone(),
    };
    let stream = event_stream(rx, snapshot, guard);

    Sse::new(stream)
        .keep_alive(KeepAlive::new().interval(Duration::from_secs(15)))
        .into_response()
}

/// Drops the session's subscriber count when the SSE stream ends, however it
/// ends. Without this a closed tab would look like a listener forever and its
/// turn would never be reaped.
struct SubscriberGuard {
    relay: Arc<Relay>,
    session_id: String,
}

impl Drop for SubscriberGuard {
    fn drop(&mut self) {
        self.relay.unsubscribe(&self.session_id);
    }
}

struct StreamState {
    rx: broadcast::Receiver<RemoteEvent>,
    guard: SubscriberGuard,
    /// The snapshot to send before anything else, so a reconnecting client is
    /// in sync from its first frame.
    pending: Option<RemoteEvent>,
}

fn event_stream(
    rx: broadcast::Receiver<RemoteEvent>,
    snapshot: RemoteEvent,
    guard: SubscriberGuard,
) -> impl Stream<Item = Result<Event, Infallible>> {
    let state = StreamState {
        rx,
        guard,
        pending: Some(snapshot),
    };
    futures_util::stream::unfold(state, |mut state| async move {
        loop {
            if let Some(event) = state.pending.take() {
                return Some((Ok(sse_event(&event)), state));
            }
            match state.rx.recv().await {
                Ok(event) => return Some((Ok(sse_event(&event)), state)),
                // A slow reader missed deltas. Deltas are suffixes, so the gap
                // cannot be papered over — resend the whole buffer instead.
                Err(broadcast::error::RecvError::Lagged(_)) => {
                    state.pending = state.guard.relay.snapshot(&state.guard.session_id);
                    // No snapshot means the session is gone; the stream ends
                    // rather than spinning on a receiver nobody will feed.
                    state.pending.as_ref()?;
                }
                Err(broadcast::error::RecvError::Closed) => return None,
            }
        }
    })
}

fn sse_event(event: &RemoteEvent) -> Event {
    match Event::default().json_data(event) {
        Ok(e) => e,
        // Serialising our own enum cannot realistically fail, but a stream that
        // dies on it would be a mystery; a visible error frame is not.
        Err(e) => Event::default().data(format!(r#"{{"type":"error","message":"{e}"}}"#)),
    }
}

const NO_TOKEN_PAGE: &str = r#"<!doctype html>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Haruspex</title>
<style>body{font:16px/1.5 system-ui,sans-serif;max-width:32rem;margin:20vh auto;padding:0 1.5rem;color:#222}</style>
<h1>You need a link</h1>
<p>This page only opens with the link its host shared with you — the whole link,
including the part after the question mark.</p>
"#;

// Served verbatim, so the client is editable without a build step and shows up
// in a stack trace as itself.
const CLIENT_HTML: &str = include_str!("client/index.html");
const CLIENT_CSS: &str = include_str!("client/app.css");
const CLIENT_JS: &str = include_str!("client/app.js");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_blank_token_is_refused_before_binding() {
        // Guards the case where the server is enabled before a token exists:
        // binding first and validating later would put an open port on the LAN.
        let config = RemoteConfig {
            port: 0,
            token: "   ".into(),
            bind_all: false,
        };
        assert!(config.token.trim().is_empty());
    }

    #[test]
    fn relay_errors_map_to_distinguishable_statuses() {
        let status = |e: RelayError| relay_error_response(e).status();
        assert_eq!(status(RelayError::Busy), StatusCode::CONFLICT);
        assert_eq!(
            status(RelayError::RateLimited),
            StatusCode::TOO_MANY_REQUESTS
        );
        assert_eq!(
            status(RelayError::TooManySessions),
            StatusCode::SERVICE_UNAVAILABLE
        );
        assert_eq!(status(RelayError::BadSessionId), StatusCode::BAD_REQUEST);
    }
}

#[cfg(test)]
mod http_tests {
    //! End-to-end over a real socket. The token path in particular is worth
    //! exercising as a client sees it rather than as a unit test of the
    //! comparison function — every interesting mistake here is a route wired up
    //! without the check, not a broken comparison.

    use super::*;
    use std::sync::Mutex as StdMutex;

    #[derive(Default)]
    struct RecordingSink {
        dispatched: StdMutex<Vec<PromptRequest>>,
        cancelled: StdMutex<Vec<String>>,
        answered: StdMutex<Vec<(String, Answer)>>,
        fail_dispatch: bool,
        fail_speech: bool,
    }

    impl Host for RecordingSink {
        fn dispatch(&self, request: PromptRequest) -> Result<(), String> {
            if self.fail_dispatch {
                return Err("no webview".into());
            }
            self.dispatched.lock().unwrap().push(request);
            Ok(())
        }

        fn cancel(&self, turn_id: &str) {
            self.cancelled.lock().unwrap().push(turn_id.to_string());
        }

        fn answer(&self, turn_id: &str, answer: &Answer) {
            self.answered
                .lock()
                .unwrap()
                .push((turn_id.to_string(), answer.clone()));
        }

        fn ensure_speech(&self) -> BoxFuture<Result<(), String>> {
            let fail = self.fail_speech;
            Box::pin(async move {
                if fail {
                    Err("no speech engine".to_string())
                } else {
                    Ok(())
                }
            })
        }
    }

    const TOKEN: &str = "test-token";

    async fn serve(sink: Arc<RecordingSink>) -> (String, Arc<Relay>, Running) {
        let relay = Arc::new(Relay::new());
        let running = start(
            sink,
            relay.clone(),
            RemoteConfig {
                // Port 0: the OS picks a free one, so tests never collide with
                // each other or with a real Haruspex on the dev box.
                port: 0,
                token: TOKEN.into(),
                bind_all: false,
            },
        )
        .await
        .expect("server should bind");
        let base = format!("http://127.0.0.1:{}", running.port);
        (base, relay, running)
    }

    #[tokio::test]
    async fn health_needs_no_token_but_the_rest_does() {
        let sink = Arc::new(RecordingSink::default());
        let (base, _relay, running) = serve(sink.clone()).await;
        let client = reqwest::Client::new();

        assert_eq!(
            client
                .get(format!("{base}/api/health"))
                .send()
                .await
                .unwrap()
                .status(),
            200
        );

        // Every authenticated route, with no token and with a wrong one.
        for token in ["", "wrong-token"] {
            let suffix = if token.is_empty() {
                String::new()
            } else {
                format!("?t={token}")
            };
            let chat = client
                .post(format!("{base}/api/chat{suffix}"))
                .json(&serde_json::json!({ "sessionId": "s1", "message": "hi" }))
                .send()
                .await
                .unwrap();
            assert_eq!(chat.status(), 401, "chat accepted token {token:?}");

            let stream = client
                .get(format!("{base}/api/stream/s1{suffix}"))
                .send()
                .await
                .unwrap();
            assert_eq!(stream.status(), 401, "stream accepted token {token:?}");

            let cancel = client
                .post(format!("{base}/api/cancel{suffix}"))
                .json(&serde_json::json!({ "sessionId": "s1" }))
                .send()
                .await
                .unwrap();
            assert_eq!(cancel.status(), 401, "cancel accepted token {token:?}");
        }

        assert!(sink.dispatched.lock().unwrap().is_empty());
        running.stop();
    }

    #[tokio::test]
    async fn an_unauthenticated_visitor_gets_no_chat_box_and_no_information() {
        let (base, _relay, running) = serve(Arc::new(RecordingSink::default())).await;
        let response = reqwest::get(&base).await.unwrap();
        // No cookie is handed out to someone who did not prove they had a link.
        assert!(response.headers().get("set-cookie").is_none());
        let body = response.text().await.unwrap();
        assert!(body.contains("You need a link"));
        // No chat box, and nothing about the machine or who owns it.
        assert!(!body.contains("id=\"composer\""));
        assert!(!body.contains(&host_name()));
        running.stop();
    }

    #[tokio::test]
    async fn a_valid_link_serves_the_client_and_remembers_it() {
        let (base, _relay, running) = serve(Arc::new(RecordingSink::default())).await;
        let response = reqwest::get(format!("{base}/?t={TOKEN}")).await.unwrap();
        let cookie = response
            .headers()
            .get("set-cookie")
            .expect("a guest with a valid link gets a cookie")
            .to_str()
            .unwrap()
            .to_string();
        assert!(cookie.contains("SameSite=Strict"));

        let body = response.text().await.unwrap();
        assert!(body.contains("id=\"composer\""));
        // The notice naming whose machine this is must survive templating.
        assert!(body.contains(&host_name()), "hostname not interpolated");
        assert!(!body.contains("{{host}}"));

        // And the cookie alone is enough next time, which is what makes a
        // bookmark or a home-screen shortcut work.
        let client = reqwest::Client::new();
        let bookmarked = client
            .get(&base)
            .header("Cookie", cookie)
            .send()
            .await
            .unwrap()
            .text()
            .await
            .unwrap();
        assert!(bookmarked.contains("id=\"composer\""));
        running.stop();
    }

    #[tokio::test]
    async fn the_client_assets_are_served_with_their_own_types() {
        let (base, _relay, running) = serve(Arc::new(RecordingSink::default())).await;
        for (path, expected) in [("/app.css", "text/css"), ("/app.js", "text/javascript")] {
            let response = reqwest::get(format!("{base}{path}")).await.unwrap();
            assert_eq!(response.status(), 200, "{path}");
            let content_type = response
                .headers()
                .get("content-type")
                .unwrap()
                .to_str()
                .unwrap()
                .to_string();
            assert!(
                content_type.starts_with(expected),
                "{path} was {content_type}"
            );
            // A guest holding a stale script against a newer API is a bug
            // nobody diagnoses over the phone.
            assert_eq!(
                response.headers().get("cache-control").unwrap(),
                "no-store, must-revalidate",
                "{path}"
            );
            assert!(
                !response.text().await.unwrap().is_empty(),
                "{path} was empty"
            );
        }
        running.stop();
    }

    #[tokio::test]
    async fn a_prompt_reaches_the_sink_and_streams_back() {
        let sink = Arc::new(RecordingSink::default());
        let (base, relay, running) = serve(sink.clone()).await;
        let client = reqwest::Client::new();

        let mut stream = client
            .get(format!("{base}/api/stream/s1?t={TOKEN}"))
            .send()
            .await
            .unwrap();
        assert_eq!(stream.status(), 200);
        // First frame is always a snapshot, so a client is in sync before it
        // has seen a single delta.
        let first = String::from_utf8_lossy(&stream.chunk().await.unwrap().unwrap()).to_string();
        assert!(first.contains("\"type\":\"snapshot\""), "got {first}");

        let accepted = client
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "what is a haruspex?" }))
            .send()
            .await
            .unwrap();
        assert_eq!(accepted.status(), 202);

        let dispatched = sink.dispatched.lock().unwrap().clone();
        assert_eq!(dispatched.len(), 1);
        assert_eq!(dispatched[0].message, "what is a haruspex?");
        assert_eq!(dispatched[0].session_id, "s1");

        // Now play the part of the frontend driver.
        relay
            .push_step(
                &dispatched[0].turn_id,
                super::super::relay::Step {
                    id: "c1".into(),
                    label: "Searching the web".into(),
                    status: super::super::relay::StepStatus::Running,
                },
            )
            .unwrap();
        relay
            .push_text(&dispatched[0].turn_id, "a reader of")
            .unwrap();
        relay
            .finish(&dispatched[0].turn_id, "a reader of entrails".into())
            .unwrap();

        let mut seen = String::new();
        while !seen.contains("\"type\":\"done\"") {
            match stream.chunk().await.unwrap() {
                Some(bytes) => seen.push_str(&String::from_utf8_lossy(&bytes)),
                None => panic!("stream ended before the answer: {seen}"),
            }
        }
        // The wire format the client switches on, proven end to end rather
        // than only in the relay's own tests.
        assert!(
            seen.contains("\"type\":\"step\""),
            "no step event in {seen}"
        );
        assert!(
            seen.contains("Searching the web"),
            "no step label in {seen}"
        );
        assert!(seen.contains("a reader of"), "no delta in {seen}");
        assert!(seen.contains("entrails"), "no final text in {seen}");
        running.stop();
    }

    #[tokio::test]
    async fn a_prompt_nobody_can_run_fails_instead_of_hanging() {
        let sink = Arc::new(RecordingSink {
            fail_dispatch: true,
            ..Default::default()
        });
        let (base, relay, running) = serve(sink).await;
        let response = reqwest::Client::new()
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "hi" }))
            .send()
            .await
            .unwrap();
        assert_eq!(response.status(), 503);
        // And the turn is not left sitting in the relay marked as in flight.
        assert_eq!(relay.in_flight_turn("s1"), None);
        running.stop();
    }

    #[tokio::test]
    async fn cancel_reaches_the_sink_only_when_there_is_something_to_stop() {
        let sink = Arc::new(RecordingSink::default());
        let (base, _relay, running) = serve(sink.clone()).await;
        let client = reqwest::Client::new();

        let idle = client
            .post(format!("{base}/api/cancel?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1" }))
            .send()
            .await
            .unwrap();
        assert_eq!(idle.status(), 204);
        assert!(sink.cancelled.lock().unwrap().is_empty());

        client
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "hi" }))
            .send()
            .await
            .unwrap();
        let busy = client
            .post(format!("{base}/api/cancel?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1" }))
            .send()
            .await
            .unwrap();
        assert_eq!(busy.status(), 202);
        assert_eq!(sink.cancelled.lock().unwrap().len(), 1);
        running.stop();
    }

    #[tokio::test]
    async fn oversized_and_empty_prompts_are_refused() {
        let (base, _relay, running) = serve(Arc::new(RecordingSink::default())).await;
        let client = reqwest::Client::new();

        let empty = client
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "   " }))
            .send()
            .await
            .unwrap();
        assert_eq!(empty.status(), 400);

        let huge = client
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({
                "sessionId": "s1",
                "message": "x".repeat(MAX_MESSAGE_BYTES + 1)
            }))
            .send()
            .await
            .unwrap();
        assert_eq!(huge.status(), 413);
        running.stop();
    }

    #[tokio::test]
    async fn rotating_the_token_cuts_off_the_old_link() {
        // Rotation is the whole of revocation here, so it has to actually
        // revoke: a link that still works after the host rotated it would make
        // the button a lie.
        let relay = Arc::new(Relay::new());
        let first = start(
            Arc::new(RecordingSink::default()),
            relay.clone(),
            RemoteConfig {
                port: 0,
                token: "old-token".into(),
                bind_all: false,
            },
        )
        .await
        .unwrap();
        let old_base = format!("http://127.0.0.1:{}", first.port);
        assert_eq!(
            reqwest::get(format!("{old_base}/?t=old-token"))
                .await
                .unwrap()
                .status(),
            200
        );

        first.stop();
        for _ in 0..50 {
            if reqwest::get(format!("{old_base}/api/health"))
                .await
                .is_err()
            {
                break;
            }
            tokio::time::sleep(Duration::from_millis(20)).await;
        }

        let second = start(
            Arc::new(RecordingSink::default()),
            relay,
            RemoteConfig {
                port: 0,
                token: "new-token".into(),
                bind_all: false,
            },
        )
        .await
        .unwrap();
        let base = format!("http://127.0.0.1:{}", second.port);

        let old = reqwest::Client::new()
            .post(format!("{base}/api/chat?t=old-token"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "hi" }))
            .send()
            .await
            .unwrap();
        assert_eq!(old.status(), 401, "the old link still worked");

        let new = reqwest::Client::new()
            .post(format!("{base}/api/chat?t=new-token"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "hi" }))
            .send()
            .await
            .unwrap();
        assert_eq!(new.status(), 202);
        second.stop();
    }

    #[tokio::test]
    async fn an_answer_reaches_the_turn_that_is_waiting_on_it() {
        use super::super::relay::{Question, QuestionOption};

        let sink = Arc::new(RecordingSink::default());
        let (base, relay, running) = serve(sink.clone()).await;
        let client = reqwest::Client::new();

        client
            .post(format!("{base}/api/chat?t={TOKEN}"))
            .json(&serde_json::json!({ "sessionId": "s1", "message": "five up top" }))
            .send()
            .await
            .unwrap();
        let turn_id = sink.dispatched.lock().unwrap()[0].turn_id.clone();
        relay
            .ask(
                &turn_id,
                Question {
                    id: "q1".into(),
                    question: "Five of what?".into(),
                    options: vec![QuestionOption {
                        label: "Fingers".into(),
                        description: None,
                        recommended: false,
                    }],
                    allow_multiple: false,
                },
            )
            .unwrap();

        let accepted = client
            .post(format!("{base}/api/answer?t={TOKEN}"))
            .json(&serde_json::json!({
                "sessionId": "s1",
                "questionId": "q1",
                "labels": ["Fingers"]
            }))
            .send()
            .await
            .unwrap();
        assert_eq!(accepted.status(), 202);

        let answered = sink.answered.lock().unwrap().clone();
        assert_eq!(answered.len(), 1);
        assert_eq!(answered[0].0, turn_id);
        assert_eq!(answered[0].1.labels, vec!["Fingers".to_string()]);

        // A second tap lands on a question nobody is waiting for: accepted
        // quietly, delivered to nobody.
        let again = client
            .post(format!("{base}/api/answer?t={TOKEN}"))
            .json(&serde_json::json!({
                "sessionId": "s1",
                "questionId": "q1",
                "labels": ["Fingers"]
            }))
            .send()
            .await
            .unwrap();
        assert_eq!(again.status(), 204);
        assert_eq!(sink.answered.lock().unwrap().len(), 1);
        running.stop();
    }

    #[tokio::test]
    async fn an_answer_needs_a_token() {
        let sink = Arc::new(RecordingSink::default());
        let (base, _relay, running) = serve(sink.clone()).await;
        let response = reqwest::Client::new()
            .post(format!("{base}/api/answer"))
            .json(&serde_json::json!({ "sessionId": "s1", "questionId": "q1", "labels": [] }))
            .send()
            .await
            .unwrap();
        assert_eq!(response.status(), 401);
        assert!(sink.answered.lock().unwrap().is_empty());
        running.stop();
    }

    #[tokio::test]
    async fn speech_starts_the_sidecar_before_giving_up_on_it() {
        // The app starts koko lazily, so a guest tapping Listen on a machine
        // whose owner has not used speech this session must trigger the same
        // startup the host's own button would.
        let sink = Arc::new(RecordingSink::default());
        let (base, _relay, running) = serve(sink).await;
        let response = reqwest::Client::new()
            .post(format!("{base}/api/speak?t={TOKEN}"))
            .json(&serde_json::json!({ "text": "hello" }))
            .send()
            .await
            .unwrap();
        // No sidecar exists in a test, so this still fails — but it fails
        // having tried, and says so differently from a host with no engine.
        assert_eq!(response.status(), 503);
        assert_eq!(response.text().await.unwrap(), "speech is not available");
        running.stop();
    }

    #[tokio::test]
    async fn speech_that_cannot_start_says_so_plainly() {
        let sink = Arc::new(RecordingSink {
            fail_speech: true,
            ..Default::default()
        });
        let (base, _relay, running) = serve(sink).await;
        let response = reqwest::Client::new()
            .post(format!("{base}/api/speak?t={TOKEN}"))
            .json(&serde_json::json!({ "text": "hello" }))
            .send()
            .await
            .unwrap();
        assert_eq!(response.status(), 503);
        assert!(response.text().await.unwrap().contains("could not start"));
        running.stop();
    }

    #[tokio::test]
    async fn speech_needs_a_token_and_something_to_say() {
        let (base, _relay, running) = serve(Arc::new(RecordingSink::default())).await;
        let client = reqwest::Client::new();

        let unauthenticated = client
            .post(format!("{base}/api/speak"))
            .json(&serde_json::json!({ "text": "hello" }))
            .send()
            .await
            .unwrap();
        assert_eq!(unauthenticated.status(), 401);

        let empty = client
            .post(format!("{base}/api/speak?t={TOKEN}"))
            .json(&serde_json::json!({ "text": "   " }))
            .send()
            .await
            .unwrap();
        assert_eq!(empty.status(), 400);
        running.stop();
    }

    #[tokio::test]
    async fn a_stopped_server_stops_answering() {
        let (base, _relay, running) = serve(Arc::new(RecordingSink::default())).await;
        assert!(reqwest::get(format!("{base}/api/health")).await.is_ok());
        running.stop();

        // Graceful shutdown is not instant; poll rather than sleep-and-hope.
        for _ in 0..50 {
            if reqwest::get(format!("{base}/api/health")).await.is_err() {
                return;
            }
            tokio::time::sleep(Duration::from_millis(20)).await;
        }
        panic!("server still answering after stop");
    }
}

#[cfg(test)]
mod wav_tests {
    use super::*;

    #[test]
    fn pcm_is_wrapped_in_a_header_a_browser_will_play() {
        let pcm = vec![0u8; 480]; // 10ms at 24kHz, 16-bit mono
        let wav = wav_from_pcm(&pcm);

        assert_eq!(&wav[0..4], b"RIFF");
        assert_eq!(&wav[8..12], b"WAVE");
        assert_eq!(&wav[36..40], b"data");
        assert_eq!(wav.len(), 44 + pcm.len());
        // The two fields a player actually reads back, little-endian.
        assert_eq!(u32::from_le_bytes(wav[4..8].try_into().unwrap()), 36 + 480);
        assert_eq!(u32::from_le_bytes(wav[24..28].try_into().unwrap()), 24_000);
        assert_eq!(u32::from_le_bytes(wav[40..44].try_into().unwrap()), 480);
    }

    #[test]
    fn an_empty_stream_still_produces_a_valid_header() {
        let wav = wav_from_pcm(&[]);
        assert_eq!(wav.len(), 44);
        assert_eq!(u32::from_le_bytes(wav[40..44].try_into().unwrap()), 0);
    }
}
