//! One configured CalDAV/CardDAV account.
//!
//! Mirrors `EmailAccount` in `integrations/email/auth.rs` deliberately — a
//! frontend-generated UUID as the stable key, a human label, a per-account
//! `enabled` toggle, camelCase serde so one object round-trips through
//! `invoke` untranslated, and credentials in the settings blob at the same
//! trust level as the existing IMAP passwords. A user who has added an email
//! account should find nothing surprising here.
//!
//! # Auth is basic / app-password only
//!
//! No OAuth is added to the tree. That covers Nextcloud, Fastmail, iCloud,
//! Radicale, Baikal and Synology — the self-hosted and privacy-oriented
//! services this app exists for.
//!
//! **Google Calendar is deliberately not supported here.** Its CalDAV endpoint
//! requires OAuth2, and the project's own rule is that anything Google-shaped
//! ships as a curated MCP config rather than a hand-built integration. The UI
//! says so, because a user who types a Google address and watches it fail with
//! a generic authentication error is a support burden that one sentence
//! prevents.

use serde::{Deserialize, Serialize};

/// A server the account talks to, for both calendars and (from Phase 11)
/// contacts. One account, one set of credentials, both collection types —
/// which is how every server this targets actually works.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ts_rs::TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct DavAccount {
    /// Stable UUID, generated by the frontend when the user adds the account.
    /// The lookup key, so relabelling does not break an in-flight tool call.
    pub id: String,

    /// Human-facing label ("Work", "Fastmail"). The model matches user intent
    /// like "what's on my work calendar" against this.
    pub label: String,

    /// Master per-account toggle. When false the account is invisible to the
    /// agent and does not contribute to the "calendar tools are available"
    /// check.
    pub enabled: bool,

    /// What the user typed: an email-like address, or a server URL. Discovery
    /// accepts either; see `discovery.rs`.
    pub address: String,

    /// SASL username. Often the same as `address`, but not always — Fastmail
    /// wants the full address while some self-hosted setups want a bare
    /// username, and guessing wrong produces an auth failure nobody can debug.
    pub username: String,

    /// App password, plaintext, in the settings blob. See the module docs.
    pub password: String,

    /// A URL the user supplied by hand, skipping discovery.
    ///
    /// Not a fallback but an override: plenty of self-hosted setups have
    /// partial discovery — no SRV record, a `.well-known` that 404s — and a
    /// user who knows their URL should not be blocked by the server's
    /// omissions.
    #[serde(default)]
    pub calendar_url: Option<String>,

    /// The same override for contacts. Phase 11 reads it; stored now so that
    /// phase needs no settings migration.
    #[serde(default)]
    pub contacts_url: Option<String>,
}

impl DavAccount {
    /// The `Authorization` header value for this account.
    pub fn auth_header(&self) -> String {
        use base64::Engine;
        let raw = format!("{}:{}", self.username, self.password);
        format!(
            "Basic {}",
            base64::engine::general_purpose::STANDARD.encode(raw)
        )
    }

    /// Whether this account can be used at all: switched on, and with enough
    /// to authenticate. Checked before a request rather than after, so an
    /// account half-filled-in produces a message about the missing field
    /// instead of a 401.
    pub fn is_usable(&self) -> bool {
        self.enabled
            && !self.address.trim().is_empty()
            && !self.username.trim().is_empty()
            && !self.password.is_empty()
    }

    /// Whether this address is one whose CalDAV needs OAuth, which this
    /// integration deliberately does not do.
    ///
    /// Matched on the host of an email-like address, so `me@gmail.com` is
    /// caught while a self-hosted server that merely *mentions* Google in a
    /// path is not.
    pub fn needs_oauth(&self) -> bool {
        oauth_only_host(&self.address)
    }
}

/// Hosts whose CalDAV is OAuth-only.
const OAUTH_ONLY_HOSTS: [&str; 3] = ["gmail.com", "googlemail.com", "google.com"];

pub fn oauth_only_host(address: &str) -> bool {
    let host = address
        .trim()
        .rsplit_once('@')
        .map(|(_, h)| h)
        .unwrap_or_else(|| address.trim())
        .trim_end_matches('/')
        .to_ascii_lowercase();
    OAUTH_ONLY_HOSTS
        .iter()
        .any(|h| host == *h || host.ends_with(&format!(".{h}")))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn account() -> DavAccount {
        DavAccount {
            id: "11111111-1111-1111-1111-111111111111".into(),
            label: "Fastmail".into(),
            enabled: true,
            address: "me@fastmail.com".into(),
            username: "me@fastmail.com".into(),
            password: "app-password".into(),
            calendar_url: None,
            contacts_url: None,
        }
    }

    #[test]
    fn the_auth_header_is_basic_and_base64() {
        // "me@fastmail.com:app-password"
        assert_eq!(
            account().auth_header(),
            "Basic bWVAZmFzdG1haWwuY29tOmFwcC1wYXNzd29yZA=="
        );
    }

    #[test]
    fn the_username_is_separate_from_the_address() {
        // Fastmail wants the full address; some self-hosted setups want a bare
        // username. Deriving one from the other produces an auth failure the
        // user cannot debug.
        let bare = DavAccount {
            username: "tim".into(),
            ..account()
        };
        assert!(bare.auth_header().starts_with("Basic "));
        assert_ne!(bare.auth_header(), account().auth_header());
    }

    #[test]
    fn an_account_is_unusable_until_it_has_what_it_needs() {
        assert!(account().is_usable());
        assert!(!DavAccount {
            enabled: false,
            ..account()
        }
        .is_usable());
        assert!(!DavAccount {
            password: String::new(),
            ..account()
        }
        .is_usable());
        assert!(!DavAccount {
            username: "   ".into(),
            ..account()
        }
        .is_usable());
    }

    #[test]
    fn google_addresses_are_recognised_as_oauth_only() {
        // Caught before a request, so the user gets "use the MCP integration"
        // rather than a bare 401.
        for address in [
            "me@gmail.com",
            "me@googlemail.com",
            "me@GMAIL.COM",
            "me@corp.google.com",
        ] {
            assert!(oauth_only_host(address), "{address} should be recognised");
        }
    }

    #[test]
    fn a_self_hosted_server_is_not_mistaken_for_google() {
        // Matched on the host, not on the string containing "google".
        for address in [
            "me@nextcloud.example.com",
            "https://dav.example.com/google/",
            "me@notgmail.com",
            "me@fastmail.com",
        ] {
            assert!(!oauth_only_host(address), "{address} is not Google");
        }
    }

    #[test]
    fn an_older_settings_blob_without_the_url_overrides_still_loads() {
        let stored = serde_json::json!({
            "id": "abc",
            "label": "Home",
            "enabled": true,
            "address": "me@example.com",
            "username": "me",
            "password": "pw"
        });
        let parsed: DavAccount = serde_json::from_value(stored).unwrap();
        assert!(parsed.calendar_url.is_none());
        assert!(parsed.contacts_url.is_none());
    }
}
