//! One configured CalDAV/CardDAV account.
//!
//! Mirrors `EmailAccount` in `integrations/email/auth.rs` deliberately — a
//! frontend-generated UUID as the stable key, a human label, a per-account
//! `enabled` toggle, camelCase serde so one object round-trips through
//! `invoke` untranslated, and credentials in the settings blob at the same
//! trust level as the existing IMAP passwords. A user who has added an email
//! account should find nothing surprising here.
//!
//! # Auth is basic / app-password only
//!
//! No OAuth is added to the tree. That covers Nextcloud, Fastmail, iCloud,
//! Radicale, Baikal and Synology — the self-hosted and privacy-oriented
//! services this app exists for.
//!
//! **Google's CalDAV endpoint requires OAuth2**, so a Google address is caught
//! before it fails with a generic authentication error. A Google calendar can
//! still be added read-only as a calendar link — see [`DavKind::Ics`].

use serde::{Deserialize, Serialize};

/// What sort of account this is.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize, ts_rs::TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub enum DavKind {
    /// A CalDAV/CardDAV server, signed in with a username and app password.
    #[default]
    Dav,
    /// A read-only calendar link: an iCalendar feed at a URL, such as Google
    /// Calendar's "secret address in iCal format". The URL is the credential —
    /// anyone holding it can read the calendar — so it is kept where a
    /// password would be (`password` / `password_ref`), never in `address`.
    Ics,
}

/// A server the account talks to, for both calendars and (from Phase 11)
/// contacts. One account, one set of credentials, both collection types —
/// which is how every server this targets actually works.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, ts_rs::TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct DavAccount {
    /// Stable UUID, generated by the frontend when the user adds the account.
    /// The lookup key, so relabelling does not break an in-flight tool call.
    pub id: String,

    /// Server account or calendar link. Absent in settings saved before links
    /// existed, which were all server accounts.
    #[serde(default)]
    #[ts(optional)]
    pub kind: Option<DavKind>,

    /// Human-facing label ("Work", "Fastmail"). The model matches user intent
    /// like "what's on my work calendar" against this.
    pub label: String,

    /// Master per-account toggle. When false the account is invisible to the
    /// agent and does not contribute to the "calendar tools are available"
    /// check.
    pub enabled: bool,

    /// What the user typed: an email-like address, or a server URL. Discovery
    /// accepts either; see `discovery.rs`.
    pub address: String,

    /// SASL username. Often the same as `address`, but not always — Fastmail
    /// wants the full address while some self-hosted setups want a bare
    /// username, and guessing wrong produces an auth failure nobody can debug.
    pub username: String,

    /// App password, inline. Empty when it is kept in the secret store under
    /// `password_ref` — the usual case. Inline only where no store works.
    pub password: String,

    /// The secret-store key holding the password (`"dav:<id>"`). Rust reads
    /// it back just before connecting; see [`DavAccount::resolved`].
    #[serde(default)]
    #[ts(optional)]
    pub password_ref: Option<String>,

    /// A URL the user supplied by hand, skipping discovery.
    ///
    /// Not a fallback but an override: plenty of self-hosted setups have
    /// partial discovery — no SRV record, a `.well-known` that 404s — and a
    /// user who knows their URL should not be blocked by the server's
    /// omissions.
    #[serde(default)]
    pub calendar_url: Option<String>,

    /// The same override for contacts.
    #[serde(default)]
    pub contacts_url: Option<String>,

    /// What the server was last seen to offer, recorded by the settings
    /// "Check" button.
    ///
    /// `None` means nobody has looked yet, and is treated as "assume both" —
    /// a user who never pressed Check must still get their tools, and the
    /// query itself reports honestly when a collection is not there. Recording
    /// it at all is what keeps an account that serves calendars but not
    /// contacts from offering a broken half.
    #[serde(default)]
    pub has_calendars: Option<bool>,
    #[serde(default)]
    pub has_contacts: Option<bool>,
}

/// By hand, so a `{:?}` in a log or an error never prints the password.
impl std::fmt::Debug for DavAccount {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let Self {
            id,
            kind,
            label,
            enabled,
            address,
            username,
            password,
            password_ref,
            calendar_url,
            contacts_url,
            has_calendars,
            has_contacts,
        } = self;
        f.debug_struct("DavAccount")
            .field("id", id)
            .field("kind", kind)
            .field("label", label)
            .field("enabled", enabled)
            .field("address", address)
            .field("username", username)
            .field("password", &crate::text_util::redacted(password))
            .field("password_ref", password_ref)
            .field("calendar_url", calendar_url)
            .field("contacts_url", contacts_url)
            .field("has_calendars", has_calendars)
            .field("has_contacts", has_contacts)
            .finish()
    }
}

impl DavAccount {
    /// The `Authorization` header value for this account.
    pub fn auth_header(&self) -> String {
        use base64::Engine;
        let raw = format!("{}:{}", self.username, self.password);
        format!(
            "Basic {}",
            base64::engine::general_purpose::STANDARD.encode(raw)
        )
    }

    /// Whether this account can be used at all: switched on, and with enough
    /// to authenticate. Checked before a request rather than after, so an
    /// account half-filled-in produces a message about the missing field
    /// instead of a 401.
    pub fn is_usable(&self) -> bool {
        if self.is_link() {
            return self.enabled && (!self.password.is_empty() || self.password_ref.is_some());
        }
        self.enabled
            && !self.address.trim().is_empty()
            && !self.username.trim().is_empty()
            && (!self.password.is_empty() || self.password_ref.is_some())
    }

    /// This account with its password read from the secret store, when it is
    /// kept there. Called just before connecting, so the password crosses
    /// from the store to the request and nowhere else.
    pub async fn resolved(&self) -> Result<DavAccount, String> {
        match self.password_ref.as_deref() {
            Some(key) if self.password.is_empty() => Ok(DavAccount {
                password: crate::secrets::require(key, &format!("password for {}", self.label))
                    .await?,
                ..self.clone()
            }),
            _ => Ok(self.clone()),
        }
    }

    /// Whether this is a read-only calendar link rather than a server account.
    pub fn is_link(&self) -> bool {
        self.kind == Some(DavKind::Ics)
    }

    /// Whether calendar tools should reach this account.
    ///
    /// Unknown counts as yes: gating on an absent check would hide a working
    /// calendar from a user who simply never pressed the button.
    pub fn serves_calendars(&self) -> bool {
        self.is_usable() && self.has_calendars.unwrap_or(true)
    }

    /// The same for contacts.
    pub fn serves_contacts(&self) -> bool {
        !self.is_link() && self.is_usable() && self.has_contacts.unwrap_or(true)
    }

    /// Whether this address is one whose CalDAV needs OAuth, which this
    /// integration deliberately does not do.
    ///
    /// Matched on the host of an email-like address, so `me@gmail.com` is
    /// caught while a self-hosted server that merely *mentions* Google in a
    /// path is not.
    pub fn needs_oauth(&self) -> bool {
        !self.is_link() && oauth_only_host(&self.address)
    }
}

/// Hosts whose CalDAV is OAuth-only.
const OAUTH_ONLY_HOSTS: [&str; 3] = ["gmail.com", "googlemail.com", "google.com"];

pub fn oauth_only_host(address: &str) -> bool {
    let host = address
        .trim()
        .rsplit_once('@')
        .map(|(_, h)| h)
        .unwrap_or_else(|| address.trim())
        .trim_end_matches('/')
        .to_ascii_lowercase();
    OAUTH_ONLY_HOSTS
        .iter()
        .any(|h| host == *h || host.ends_with(&format!(".{h}")))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn account() -> DavAccount {
        DavAccount {
            id: "11111111-1111-1111-1111-111111111111".into(),
            kind: None,
            label: "Fastmail".into(),
            enabled: true,
            address: "me@fastmail.com".into(),
            username: "me@fastmail.com".into(),
            password: "app-password".into(),
            password_ref: None,
            calendar_url: None,
            contacts_url: None,
            has_calendars: None,
            has_contacts: None,
        }
    }

    #[test]
    fn debug_never_prints_the_password() {
        let shown = format!("{:?}", account());
        assert!(!shown.contains("app-password"), "{shown}");
        assert!(shown.contains("me@fastmail.com"), "{shown}");
    }

    #[test]
    fn the_auth_header_is_basic_and_base64() {
        // "me@fastmail.com:app-password"
        assert_eq!(
            account().auth_header(),
            "Basic bWVAZmFzdG1haWwuY29tOmFwcC1wYXNzd29yZA=="
        );
    }

    #[test]
    fn the_username_is_separate_from_the_address() {
        // Fastmail wants the full address; some self-hosted setups want a bare
        // username. Deriving one from the other produces an auth failure the
        // user cannot debug.
        let bare = DavAccount {
            username: "tim".into(),
            ..account()
        };
        assert!(bare.auth_header().starts_with("Basic "));
        assert_ne!(bare.auth_header(), account().auth_header());
    }

    #[test]
    fn an_account_is_unusable_until_it_has_what_it_needs() {
        assert!(account().is_usable());
        assert!(!DavAccount {
            enabled: false,
            ..account()
        }
        .is_usable());
        assert!(!DavAccount {
            password: String::new(),
            ..account()
        }
        .is_usable());
        assert!(!DavAccount {
            username: "   ".into(),
            ..account()
        }
        .is_usable());
    }

    #[test]
    fn google_addresses_are_recognised_as_oauth_only() {
        // Caught before a request, so the user gets "use the MCP integration"
        // rather than a bare 401.
        for address in [
            "me@gmail.com",
            "me@googlemail.com",
            "me@GMAIL.COM",
            "me@corp.google.com",
        ] {
            assert!(oauth_only_host(address), "{address} should be recognised");
        }
    }

    #[test]
    fn a_self_hosted_server_is_not_mistaken_for_google() {
        // Matched on the host, not on the string containing "google".
        for address in [
            "me@nextcloud.example.com",
            "https://dav.example.com/google/",
            "me@notgmail.com",
            "me@fastmail.com",
        ] {
            assert!(!oauth_only_host(address), "{address} is not Google");
        }
    }

    #[test]
    fn an_unchecked_account_offers_both_rather_than_neither() {
        // Gating on an absent check would hide a working calendar from a user
        // who simply never pressed the button.
        let unchecked = account();
        assert!(unchecked.serves_calendars());
        assert!(unchecked.serves_contacts());
    }

    #[test]
    fn a_server_that_offers_one_protocol_does_not_present_the_other() {
        let calendars_only = DavAccount {
            has_calendars: Some(true),
            has_contacts: Some(false),
            ..account()
        };
        assert!(calendars_only.serves_calendars());
        assert!(!calendars_only.serves_contacts());
    }

    #[test]
    fn an_unusable_account_serves_nothing_whatever_it_was_seen_to_offer() {
        let disabled = DavAccount {
            enabled: false,
            has_calendars: Some(true),
            has_contacts: Some(true),
            ..account()
        };
        assert!(!disabled.serves_calendars());
        assert!(!disabled.serves_contacts());
    }

    #[test]
    fn an_older_settings_blob_without_the_url_overrides_still_loads() {
        let stored = serde_json::json!({
            "id": "abc",
            "label": "Home",
            "enabled": true,
            "address": "me@example.com",
            "username": "me",
            "password": "pw"
        });
        let parsed: DavAccount = serde_json::from_value(stored).unwrap();
        assert!(parsed.calendar_url.is_none());
        assert!(parsed.contacts_url.is_none());
        // An account stored before capabilities existed keeps working.
        assert!(parsed.has_calendars.is_none());
        assert!(parsed.serves_contacts());
    }

    fn link() -> DavAccount {
        DavAccount {
            kind: Some(DavKind::Ics),
            address: String::new(),
            username: String::new(),
            password: "https://calendar.google.com/calendar/ical/x/private-abc/basic.ics".into(),
            ..account()
        }
    }

    #[test]
    fn a_calendar_link_needs_only_its_url() {
        assert!(link().is_usable());
        assert!(!DavAccount {
            password: String::new(),
            ..link()
        }
        .is_usable());
        assert!(DavAccount {
            password: String::new(),
            password_ref: Some("dav:x".into()),
            ..link()
        }
        .is_usable());
    }

    #[test]
    fn a_calendar_link_serves_calendars_and_never_contacts() {
        assert!(link().serves_calendars());
        assert!(!DavAccount {
            has_contacts: Some(true),
            ..link()
        }
        .serves_contacts());
    }

    #[test]
    fn a_google_calendar_link_is_not_turned_away_as_needing_oauth() {
        let google = DavAccount {
            address: "me@gmail.com".into(),
            ..link()
        };
        assert!(!google.needs_oauth());
    }

    #[test]
    fn settings_saved_before_links_read_as_server_accounts() {
        let json = r#"{"id":"a","label":"Old","enabled":true,"address":"me@fastmail.com",
            "username":"me","password":"p"}"#;
        let old: DavAccount = serde_json::from_str(json).unwrap();
        assert!(!old.is_link());
        assert!(old.serves_contacts());
    }
}
