#!/usr/bin/env node
/**
 * IPC command-name drift guard (audit finding X2).
 *
 * Rust command names and TS `invoke()` calls are matched at runtime only —
 * a rename on either side compiles fine and fails as a chat-time tool
 * error. This script makes the link checkable:
 *
 *   1. Parses `generate_handler![...]` in src-tauri/src/lib.rs — the
 *      authoritative command list.
 *   2. Regenerates src/lib/ipc/commands.ts from it (with --write), or
 *      verifies the file is current (default; used by CI).
 *   3. Scans src/ for `invoke('name')` literals and fails on any name
 *      Rust doesn't register. Dynamic call sites must take their names
 *      from the generated IPC constant, which is correct by construction.
 *
 * Usage:  node scripts/check-ipc.mjs [--write]
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const write = process.argv.includes('--write');

// --- 1. Rust command list -------------------------------------------------
const librs = readFileSync(join(root, 'src-tauri/src/lib.rs'), 'utf8');
const handlerBlock = librs.match(/generate_handler!\[([\s\S]*?)\]/);
if (!handlerBlock) {
	console.error('check-ipc: could not find generate_handler![...] in lib.rs');
	process.exit(1);
}
// Entries are `module::path::fn_name` — the command name is the last segment.
const commandSet = new Set(
	handlerBlock[1]
		.split(',')
		.map((e) => e.trim())
		.filter(Boolean)
		.map((e) => e.split('::').pop().trim())
		.filter((e) => /^[a-z][a-z0-9_]*$/.test(e))
);

// --- 2. Generated commands.ts ---------------------------------------------
const names = [...commandSet].sort();
const generated = `// Generated by scripts/check-ipc.mjs from src-tauri/src/lib.rs — do not edit.
// Run \`node scripts/check-ipc.mjs --write\` after changing generate_handler![].
//
// Use these constants wherever a command name is dispatched dynamically
// (executor factories, command maps) so the name provably exists in Rust.

export const IPC = {
${names.map((n) => `\t${n}: '${n}'`).join(',\n')}
} as const;

export type IpcCommand = (typeof IPC)[keyof typeof IPC];
`;
const commandsPath = join(root, 'src/lib/ipc/commands.ts');
if (write) {
	writeFileSync(commandsPath, generated);
	console.log(`check-ipc: wrote ${names.length} commands to src/lib/ipc/commands.ts`);
} else {
	let current = '';
	try {
		current = readFileSync(commandsPath, 'utf8');
	} catch {
		// missing counts as stale
	}
	if (current !== generated) {
		console.error(
			'check-ipc: src/lib/ipc/commands.ts is stale. Run `node scripts/check-ipc.mjs --write`.'
		);
		process.exit(1);
	}
}

// --- 3. Scan TS/Svelte invoke literals -------------------------------------
function* walk(dir) {
	for (const entry of readdirSync(dir)) {
		const p = join(dir, entry);
		if (statSync(p).isDirectory()) {
			if (entry === 'node_modules' || entry === 'gen') continue;
			yield* walk(p);
		} else if (/\.(ts|svelte)$/.test(entry)) {
			yield p;
		}
	}
}

const invokeRe = /invoke(?:<[^>(]*>)?\(\s*['"]([a-z][a-z0-9_]*)['"]/g;
const problems = [];
let literalCount = 0;
for (const file of walk(join(root, 'src'))) {
	if (file.endsWith('.test.ts')) continue; // tests mock invoke freely
	const text = readFileSync(file, 'utf8');
	for (const m of text.matchAll(invokeRe)) {
		literalCount++;
		if (!commandSet.has(m[1])) {
			const line = text.slice(0, m.index).split('\n').length;
			problems.push(`${file.replace(root + '/', '')}:${line} — unknown command '${m[1]}'`);
		}
	}
}

if (problems.length) {
	console.error('check-ipc: TS invokes commands Rust does not register:\n' + problems.join('\n'));
	process.exit(1);
}
console.log(
	`check-ipc: OK — ${literalCount} invoke literals checked against ${commandSet.size} Rust commands`
);
