#!/bin/bash
# Record what the PINNED sd-server build can actually do.
#
# The local image backend declares its capabilities from the fixture this
# emits, rather than asserting them in TypeScript. A capability claim nobody
# checks is how a job stops degrading and starts silently shipping bad output —
# so when a version bump drops a feature, a committed fixture changing is a
# test failure instead of a surprise at 4am.
#
# Two sources, both deterministic and both requiring no model weights:
#   * `--help`, for which generation features the build was compiled with;
#   * the binary's own route table, for which HTTP API it serves.
#
# What this deliberately does NOT do is generate an image. sd-server refuses to
# start without a model, and this phase downloads no weights — so flag presence
# is the honest limit of what can be established here. It is evidence the
# feature was COMPILED IN, not that it works against a given checkpoint: the
# server reports the second at runtime on /sdcpp/v1/capabilities, once a model
# is loaded, which is where the backend checks it.
#
# Usage: ./scripts/sdcpp-capabilities.sh [--target <triple>]

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BINARIES_DIR="$PROJECT_ROOT/src-tauri/binaries"
OUT="$PROJECT_ROOT/src/lib/image/local/capabilities.json"

TARGET=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --target) TARGET="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done
[ -z "$TARGET" ] && TARGET="$(rustc --print host-tuple)"
case "$TARGET" in
    *-windows-msvc) EXT=".exe" ;;
    *)              EXT=""     ;;
esac

SD_BIN="$BINARIES_DIR/sd-server-${TARGET}${EXT}"
SD_LIBS="$BINARIES_DIR/sd-libs"
VERSION=$(cat "$BINARIES_DIR/sd-server-${TARGET}.version" 2>/dev/null || echo "")

if [ ! -x "$SD_BIN" ]; then
    echo "ERROR: $SD_BIN is missing. Run ./scripts/fetch-sdcpp.sh first."
    exit 1
fi

HELP=$(LD_LIBRARY_PATH="$SD_LIBS" "$SD_BIN" --help 2>&1 || true)

# Present in the help text = compiled in.
has() { printf '%s' "$HELP" | grep -q -- "$1" && echo true || echo false; }

IP_ADAPTER=$(has '--ip-adapter')
CIRCULAR=$(has '--circular')
LORA=$(has '--lora-model-dir')

# One `--lora-model-dir`, and LoRAs are named in the request rather than bound
# to numbered slots, so there is no compiled-in maximum to read. The backend
# reports its own limit; 0 here would read as "no LoRA support", which is the
# opposite of true.
LORA_SLOTS=$([ "$LORA" = true ] && echo 4 || echo 0)

# Routes, straight out of the binary. Sorted and de-duplicated so two runs on
# one build emit byte-identical JSON.
ROUTES=$(LC_ALL=C grep -a -o -E '/(sdapi|sdcpp|v1)/[a-zA-Z0-9_/-]+' "$SD_BIN" \
    | sort -u \
    | sed 's/.*/    "&"/' \
    | sed '$!s/$/,/')

cat > "$OUT" <<JSON
{
  "_comment": "Generated by scripts/sdcpp-capabilities.sh. Do not edit by hand; re-run it after bumping SDCPP_VERSION.",
  "version": "$VERSION",
  "capabilities": {
    "referenceConditioning": $IP_ADAPTER,
    "seamlessTiling": $CIRCULAR,
    "loras": $LORA,
    "maxLoras": $LORA_SLOTS
  },
  "flags": {
    "referenceConditioning": "--ip-adapter",
    "seamlessTiling": "--circular",
    "loras": "--lora-model-dir"
  },
  "routes": [
$ROUTES
  ]
}
JSON

echo ">> Wrote $OUT"
grep -E '"(referenceConditioning|seamlessTiling|loras|maxLoras|version)"' "$OUT" | head -6
