//! Email account credential struct.
//!
//! The frontend persists `EmailAccount` objects inside the existing
//! `AppSettings.integrations.email.accounts` array (localStorage /
//! JSON blob — same trust level as other credential-bearing settings).
//! The backend receives them as command arguments whenever it needs
//! to open a connection. The only backend state is a logged-in IMAP
//! session kept per account for a couple of minutes (`imap_client`),
//! dropped when the account is edited or its login changes.
//!
//! Design notes:
//!
//! - **Send-ready from day 1.** SMTP endpoints are part of the struct
//!   even though Phase 10.1 doesn't use them, so Phase 10.2 doesn't
//!   need a settings migration.
//! - **Multi-account.** The frontend stores an array of accounts,
//!   each with its own UUID. Tauri commands accept an optional
//!   `account_id` and look the corresponding account up — or, when
//!   omitted on list-style calls, fan out across all enabled
//!   accounts.
//! - **The password lives in the system keychain where there is one**
//!   (`crate::secrets`): the stored account carries `password_ref` and an
//!   empty `password`, and [`resolve`] reads it back inside Rust when a
//!   connection is made. Without a keychain it stays inline in the
//!   settings blob, as every other credential Haruspex holds does.

use serde::{Deserialize, Serialize};

use super::provider::{EmailProvider, TlsMode};
use crate::secrets::{Keychain, Store};

/// Credentials and endpoint configuration for a single email account.
///
/// Mirrors the TypeScript `EmailAccount` interface in
/// `src/lib/stores/settings.ts`. Field names use camelCase via serde
/// rename so a single JSON object can be produced/consumed on both
/// sides without a translation layer.
#[derive(Clone, Debug, Serialize, Deserialize, ts_rs::TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct EmailAccount {
    /// Stable UUID; generated by the frontend when the user adds
    /// the account. Used as the lookup key so renaming / changing
    /// the email address doesn't break in-progress tool references.
    pub id: String,

    /// Human-facing label ("Work Gmail", "Personal").
    pub label: String,

    /// Master per-account toggle. When false, the account is hidden
    /// from list commands and doesn't contribute to the "email tools
    /// are visible" check.
    pub enabled: bool,

    /// Separate opt-in for SMTP sending. Unused in Phase 10.1.
    /// Stored now so Phase 10.2 doesn't require a settings migration.
    pub send_enabled: bool,

    /// Which preset this account was created from, or `Custom` for
    /// user-entered hostnames.
    pub provider: EmailProvider,

    /// The email address itself — used as the SASL username and as
    /// the `From` address when sending.
    pub email_address: String,

    /// App password, inline. Empty when it is kept in the system keychain
    /// under `password_ref` — the usual case where a keychain exists.
    pub password: String,

    /// The keychain entry holding the password (`"email:<id>"`). Rust reads
    /// it when it connects; the webview never sees the value again.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub password_ref: Option<String>,

    // --- IMAP endpoint ---
    pub imap_host: String,
    pub imap_port: u16,
    pub imap_tls: TlsMode,

    // --- SMTP endpoint (Phase 10.2) ---
    pub smtp_host: String,
    pub smtp_port: u16,
    pub smtp_tls: TlsMode,
}

impl EmailAccount {
    /// Cheap structural validation — catches obvious typos before we
    /// waste a network round-trip on them. Anything more subtle
    /// (bad password, server unreachable, TLS mismatch) is reported
    /// by the live test-connection call instead.
    pub fn validate(&self) -> Result<(), String> {
        if self.id.trim().is_empty() {
            return Err("Account id is empty".into());
        }
        if self.email_address.trim().is_empty() {
            return Err("Email address is empty".into());
        }
        if !self.email_address.contains('@') {
            return Err(format!(
                "Email address {:?} does not look like an email",
                self.email_address
            ));
        }
        if self.password.is_empty() && self.password_ref.is_none() {
            return Err("Password is empty".into());
        }
        if self.imap_host.trim().is_empty() {
            return Err("IMAP host is empty".into());
        }
        if self.imap_port == 0 {
            return Err("IMAP port is zero".into());
        }
        // SMTP fields are allowed to be blank in 10.1 if send is not
        // enabled — but if the user flipped sendEnabled, require them.
        if self.send_enabled {
            if self.smtp_host.trim().is_empty() {
                return Err("SMTP host is empty but sendEnabled is true".into());
            }
            if self.smtp_port == 0 {
                return Err("SMTP port is zero but sendEnabled is true".into());
            }
        }
        Ok(())
    }
}

impl EmailAccount {
    /// This account with its password filled in from `store` when it is kept
    /// there. An inline password is used as it is.
    pub fn resolved_from(&self, store: &dyn Store) -> Result<EmailAccount, String> {
        let Some(key) = self
            .password_ref
            .as_deref()
            .filter(|_| self.password.is_empty())
        else {
            return Ok(self.clone());
        };
        match store.get(key)? {
            Some(password) => Ok(EmailAccount {
                password,
                ..self.clone()
            }),
            None => Err(format!(
                "The password for {} is missing from the system keychain — enter it again in \
                 Settings → Integrations",
                self.email_address
            )),
        }
    }
}

/// The account with its password, read from the system keychain off the
/// async runtime (see `secrets` for why).
pub async fn resolve(account: &EmailAccount) -> Result<EmailAccount, String> {
    if account.password_ref.is_none() || !account.password.is_empty() {
        return Ok(account.clone());
    }
    let account = account.clone();
    tokio::task::spawn_blocking(move || account.resolved_from(&Keychain))
        .await
        .map_err(|e| e.to_string())?
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::secrets::Memory;

    fn sample_account() -> EmailAccount {
        EmailAccount {
            id: "test-1".into(),
            label: "Test".into(),
            enabled: true,
            send_enabled: false,
            provider: EmailProvider::Gmail,
            email_address: "alice@example.com".into(),
            password: "hunter2".into(),
            password_ref: None,
            imap_host: "imap.example.com".into(),
            imap_port: 993,
            imap_tls: TlsMode::Implicit,
            smtp_host: String::new(),
            smtp_port: 0,
            smtp_tls: TlsMode::Implicit,
        }
    }

    #[test]
    fn valid_account_passes() {
        assert!(sample_account().validate().is_ok());
    }

    #[test]
    fn missing_at_sign_fails() {
        let mut a = sample_account();
        a.email_address = "not-an-email".into();
        assert!(a.validate().is_err());
    }

    #[test]
    fn send_enabled_requires_smtp() {
        let mut a = sample_account();
        a.send_enabled = true;
        assert!(a.validate().is_err());
        a.smtp_host = "smtp.example.com".into();
        a.smtp_port = 465;
        assert!(a.validate().is_ok());
    }

    #[test]
    fn empty_password_fails() {
        let mut a = sample_account();
        a.password = String::new();
        assert!(a.validate().is_err());
    }

    #[test]
    fn a_kept_password_is_read_from_the_store() {
        let store = Memory::default();
        store.set("email:test-1", "from-keychain").unwrap();
        let mut a = sample_account();
        a.password = String::new();
        a.password_ref = Some("email:test-1".into());
        assert!(a.validate().is_ok());
        assert_eq!(a.resolved_from(&store).unwrap().password, "from-keychain");
    }

    #[test]
    fn a_missing_kept_password_says_where_to_enter_it() {
        let mut a = sample_account();
        a.password = String::new();
        a.password_ref = Some("email:test-1".into());
        let err = a.resolved_from(&Memory::default()).unwrap_err();
        assert!(err.contains("alice@example.com"), "{err}");
        assert!(err.contains("Settings → Integrations"), "{err}");
    }

    #[test]
    fn an_inline_password_is_used_as_it_is() {
        let a = sample_account();
        assert_eq!(
            a.resolved_from(&Memory::default()).unwrap().password,
            "hunter2"
        );
    }
}
