//! Email account credential struct.
//!
//! The frontend persists `EmailAccount` objects inside the existing
//! `AppSettings.integrations.email.accounts` array (localStorage /
//! JSON blob — same trust level as other credential-bearing settings).
//! The backend receives them as command arguments whenever it needs
//! to open a connection. There is no server-side state: each call
//! validates + connects fresh.
//!
//! Design notes:
//!
//! - **Send-ready from day 1.** SMTP endpoints are part of the struct
//!   even though Phase 10.1 doesn't use them, so Phase 10.2 doesn't
//!   need a settings migration.
//! - **Multi-account.** The frontend stores an array of accounts,
//!   each with its own UUID. Tauri commands accept an optional
//!   `account_id` and look the corresponding account up — or, when
//!   omitted on list-style calls, fan out across all enabled
//!   accounts.
//! - **`password` field is plaintext in the struct** because it must
//!   be sent to the IMAP server. Storage confidentiality is handled
//!   at the settings-blob layer, same as every other credential
//!   Haruspex already holds (Brave key, remote inference key, etc.).

use serde::{Deserialize, Serialize};

use super::provider::{EmailProvider, TlsMode};

/// Credentials and endpoint configuration for a single email account.
///
/// Mirrors the TypeScript `EmailAccount` interface in
/// `src/lib/stores/settings.ts`. Field names use camelCase via serde
/// rename so a single JSON object can be produced/consumed on both
/// sides without a translation layer.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EmailAccount {
    /// Stable UUID; generated by the frontend when the user adds
    /// the account. Used as the lookup key so renaming / changing
    /// the email address doesn't break in-progress tool references.
    pub id: String,

    /// Human-facing label ("Work Gmail", "Personal").
    pub label: String,

    /// Master per-account toggle. When false, the account is hidden
    /// from list commands and doesn't contribute to the "email tools
    /// are visible" check.
    pub enabled: bool,

    /// Separate opt-in for SMTP sending. Unused in Phase 10.1.
    /// Stored now so Phase 10.2 doesn't require a settings migration.
    pub send_enabled: bool,

    /// Which preset this account was created from, or `Custom` for
    /// user-entered hostnames.
    pub provider: EmailProvider,

    /// The email address itself — used as the SASL username and as
    /// the `From` address when sending.
    pub email_address: String,

    /// App password (plaintext). Used as the SASL password.
    pub password: String,

    // --- IMAP endpoint ---
    pub imap_host: String,
    pub imap_port: u16,
    pub imap_tls: TlsMode,

    // --- SMTP endpoint (Phase 10.2) ---
    pub smtp_host: String,
    pub smtp_port: u16,
    pub smtp_tls: TlsMode,
}

impl EmailAccount {
    /// Cheap structural validation — catches obvious typos before we
    /// waste a network round-trip on them. Anything more subtle
    /// (bad password, server unreachable, TLS mismatch) is reported
    /// by the live test-connection call instead.
    pub fn validate(&self) -> Result<(), String> {
        if self.id.trim().is_empty() {
            return Err("Account id is empty".into());
        }
        if self.email_address.trim().is_empty() {
            return Err("Email address is empty".into());
        }
        if !self.email_address.contains('@') {
            return Err(format!(
                "Email address {:?} does not look like an email",
                self.email_address
            ));
        }
        if self.password.is_empty() {
            return Err("Password is empty".into());
        }
        if self.imap_host.trim().is_empty() {
            return Err("IMAP host is empty".into());
        }
        if self.imap_port == 0 {
            return Err("IMAP port is zero".into());
        }
        // SMTP fields are allowed to be blank in 10.1 if send is not
        // enabled — but if the user flipped sendEnabled, require them.
        if self.send_enabled {
            if self.smtp_host.trim().is_empty() {
                return Err("SMTP host is empty but sendEnabled is true".into());
            }
            if self.smtp_port == 0 {
                return Err("SMTP port is zero but sendEnabled is true".into());
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_account() -> EmailAccount {
        EmailAccount {
            id: "test-1".into(),
            label: "Test".into(),
            enabled: true,
            send_enabled: false,
            provider: EmailProvider::Gmail,
            email_address: "alice@example.com".into(),
            password: "hunter2".into(),
            imap_host: "imap.example.com".into(),
            imap_port: 993,
            imap_tls: TlsMode::Implicit,
            smtp_host: String::new(),
            smtp_port: 0,
            smtp_tls: TlsMode::Implicit,
        }
    }

    #[test]
    fn valid_account_passes() {
        assert!(sample_account().validate().is_ok());
    }

    #[test]
    fn missing_at_sign_fails() {
        let mut a = sample_account();
        a.email_address = "not-an-email".into();
        assert!(a.validate().is_err());
    }

    #[test]
    fn send_enabled_requires_smtp() {
        let mut a = sample_account();
        a.send_enabled = true;
        assert!(a.validate().is_err());
        a.smtp_host = "smtp.example.com".into();
        a.smtp_port = 465;
        assert!(a.validate().is_ok());
    }

    #[test]
    fn empty_password_fails() {
        let mut a = sample_account();
        a.password = String::new();
        assert!(a.validate().is_err());
    }
}
